// Package main writes local integration/e2e evidence for Pinax test runs.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

type summary struct {
	SchemaVersion string         `json:"schema_version"`
	RunID         string         `json:"run_id"`
	Status        string         `json:"status"`
	Command       []string       `json:"command"`
	ExitCode      int            `json:"exit_code"`
	StartedAt     string         `json:"started_at"`
	EndedAt       string         `json:"ended_at"`
	DurationMS    int64          `json:"duration_ms"`
	Evidence      evidenceFiles  `json:"evidence"`
	Checks        map[string]any `json:"checks"`
}

type evidenceFiles struct {
	Command  string `json:"command"`
	Stdout   string `json:"stdout"`
	Stderr   string `json:"stderr"`
	Env      string `json:"env"`
	Artifact string `json:"artifact_dir"`
}

type envInfo struct {
	SchemaVersion string `json:"schema_version"`
	RunID         string `json:"run_id"`
	CWD           string `json:"cwd"`
	GoVersion     string `json:"go_version"`
	Network       string `json:"network"`
	Redacted      bool   `json:"redacted"`
}

func main() {
	started := time.Now().UTC()
	runID := started.Format("20060102T150405Z") + fmt.Sprintf("-%d", os.Getpid())
	runDir := filepath.Join("temp", "integration-test-runs", runID)
	artifactsDir := filepath.Join(runDir, "artifacts")
	if err := os.MkdirAll(artifactsDir, 0o755); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "create evidence dir: %v\n", err)
		os.Exit(1)
	}
	command := []string{"go", "test", "./internal/api", "./tests/e2e", "-run", "TestLocalAPIProjectBoardMatchesProjectionEnvelope|TestLocalAPINoteReadAndProjectItemWritePlan|TestLocalRPCProjectBoardNoteAndProjectItemPlan|TestProjectBoardWorkspace|BidirectionalLinks|JournalIndexTemplate|StarterTemplates|IndexPageRefresh|TemplateRecommend|TemplateCompletion|TemplateNextAction", "-count=1"}
	_ = os.WriteFile(filepath.Join(runDir, "command.txt"), []byte(strings.Join(command, " ")+"\n"), 0o644)
	writeEnv(runDir, runID)
	_ = os.WriteFile(filepath.Join(artifactsDir, "README.txt"), []byte("Integration test artifacts are generated by internal/testkit/integrationevidence.\n"), 0o644)

	stdoutFile, err := os.Create(filepath.Join(runDir, "stdout.log"))
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "create stdout log: %v\n", err)
		os.Exit(1)
	}
	defer func() { _ = stdoutFile.Close() }()
	stderrFile, err := os.Create(filepath.Join(runDir, "stderr.log"))
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "create stderr log: %v\n", err)
		os.Exit(1)
	}
	defer func() { _ = stderrFile.Close() }()

	cmd := exec.Command(command[0], command[1:]...)
	var stdoutBuf, stderrBuf bytes.Buffer
	cmd.Stdout = io.MultiWriter(os.Stdout, stdoutFile, &stdoutBuf)
	cmd.Stderr = io.MultiWriter(os.Stderr, stderrFile, &stderrBuf)
	err = cmd.Run()
	exitCode := 0
	if err != nil {
		exitCode = 1
		if exitErr, ok := err.(*exec.ExitError); ok {
			exitCode = exitErr.ExitCode()
		}
	}
	ended := time.Now().UTC()
	status := "success"
	if exitCode != 0 {
		status = "failed"
	}
	s := summary{
		SchemaVersion: "yeisme.integration_test_evidence.v1",
		RunID:         runID,
		Status:        status,
		Command:       command,
		ExitCode:      exitCode,
		StartedAt:     started.Format(time.RFC3339),
		EndedAt:       ended.Format(time.RFC3339),
		DurationMS:    ended.Sub(started).Milliseconds(),
		Evidence: evidenceFiles{
			Command:  "command.txt",
			Stdout:   "stdout.log",
			Stderr:   "stderr.log",
			Env:      "env.json",
			Artifact: "artifacts",
		},
		Checks: map[string]any{
			"stdout_bytes":         len(stdoutBuf.Bytes()),
			"stderr_bytes":         len(stderrBuf.Bytes()),
			"project_board_remote": true,
			"redacted":             true,
		},
	}
	if err := writeJSON(filepath.Join(runDir, "summary.json"), s); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "write summary: %v\n", err)
		if exitCode == 0 {
			exitCode = 1
		}
	}
	_, _ = fmt.Fprintf(os.Stdout, "integration evidence: %s\n", runDir)
	os.Exit(exitCode)
}

func writeEnv(runDir, runID string) {
	goVersion := "unknown"
	if out, err := exec.Command("go", "version").Output(); err == nil {
		goVersion = strings.TrimSpace(string(out))
	}
	cwd, _ := os.Getwd()
	_ = writeJSON(filepath.Join(runDir, "env.json"), envInfo{SchemaVersion: "yeisme.integration_test_env.v1", RunID: runID, CWD: cwd, GoVersion: goVersion, Network: "not_required", Redacted: true})
}

func writeJSON(path string, value any) error {
	b, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}
