// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newAssetLinkRecord(db *gorm.DB, opts ...gen.DOOption) assetLinkRecord {
	_assetLinkRecord := assetLinkRecord{}

	_assetLinkRecord.assetLinkRecordDo.UseDB(db, opts...)
	_assetLinkRecord.assetLinkRecordDo.UseModel(&model.AssetLinkRecord{})

	tableName := _assetLinkRecord.assetLinkRecordDo.TableName()
	_assetLinkRecord.ALL = field.NewAsterisk(tableName)
	_assetLinkRecord.ID = field.NewUint(tableName, "id")
	_assetLinkRecord.AssetPath = field.NewString(tableName, "asset_path")
	_assetLinkRecord.SourceNoteID = field.NewString(tableName, "source_note_id")
	_assetLinkRecord.SourcePath = field.NewString(tableName, "source_path")
	_assetLinkRecord.RawReference = field.NewString(tableName, "raw_reference")
	_assetLinkRecord.LinkStyle = field.NewString(tableName, "link_style")
	_assetLinkRecord.LinkKind = field.NewString(tableName, "link_kind")
	_assetLinkRecord.Line = field.NewInt(tableName, "line")
	_assetLinkRecord.Status = field.NewString(tableName, "status")
	_assetLinkRecord.MediaType = field.NewString(tableName, "media_type")

	_assetLinkRecord.fillFieldMap()

	return _assetLinkRecord
}

type assetLinkRecord struct {
	assetLinkRecordDo

	ALL          field.Asterisk
	ID           field.Uint
	AssetPath    field.String
	SourceNoteID field.String
	SourcePath   field.String
	RawReference field.String
	LinkStyle    field.String
	LinkKind     field.String
	Line         field.Int
	Status       field.String
	MediaType    field.String

	fieldMap map[string]field.Expr
}

func (a assetLinkRecord) Table(newTableName string) *assetLinkRecord {
	a.assetLinkRecordDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a assetLinkRecord) As(alias string) *assetLinkRecord {
	a.assetLinkRecordDo.DO = *(a.assetLinkRecordDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *assetLinkRecord) updateTableName(table string) *assetLinkRecord {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint(table, "id")
	a.AssetPath = field.NewString(table, "asset_path")
	a.SourceNoteID = field.NewString(table, "source_note_id")
	a.SourcePath = field.NewString(table, "source_path")
	a.RawReference = field.NewString(table, "raw_reference")
	a.LinkStyle = field.NewString(table, "link_style")
	a.LinkKind = field.NewString(table, "link_kind")
	a.Line = field.NewInt(table, "line")
	a.Status = field.NewString(table, "status")
	a.MediaType = field.NewString(table, "media_type")

	a.fillFieldMap()

	return a
}

func (a *assetLinkRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *assetLinkRecord) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["asset_path"] = a.AssetPath
	a.fieldMap["source_note_id"] = a.SourceNoteID
	a.fieldMap["source_path"] = a.SourcePath
	a.fieldMap["raw_reference"] = a.RawReference
	a.fieldMap["link_style"] = a.LinkStyle
	a.fieldMap["link_kind"] = a.LinkKind
	a.fieldMap["line"] = a.Line
	a.fieldMap["status"] = a.Status
	a.fieldMap["media_type"] = a.MediaType
}

func (a assetLinkRecord) clone(db *gorm.DB) assetLinkRecord {
	a.assetLinkRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a assetLinkRecord) replaceDB(db *gorm.DB) assetLinkRecord {
	a.assetLinkRecordDo.ReplaceDB(db)
	return a
}

type assetLinkRecordDo struct{ gen.DO }

type IAssetLinkRecordDo interface {
	gen.SubQuery
	Debug() IAssetLinkRecordDo
	WithContext(ctx context.Context) IAssetLinkRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAssetLinkRecordDo
	WriteDB() IAssetLinkRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAssetLinkRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAssetLinkRecordDo
	Not(conds ...gen.Condition) IAssetLinkRecordDo
	Or(conds ...gen.Condition) IAssetLinkRecordDo
	Select(conds ...field.Expr) IAssetLinkRecordDo
	Where(conds ...gen.Condition) IAssetLinkRecordDo
	Order(conds ...field.Expr) IAssetLinkRecordDo
	Distinct(cols ...field.Expr) IAssetLinkRecordDo
	Omit(cols ...field.Expr) IAssetLinkRecordDo
	Join(table schema.Tabler, on ...field.Expr) IAssetLinkRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAssetLinkRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAssetLinkRecordDo
	Group(cols ...field.Expr) IAssetLinkRecordDo
	Having(conds ...gen.Condition) IAssetLinkRecordDo
	Limit(limit int) IAssetLinkRecordDo
	Offset(offset int) IAssetLinkRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAssetLinkRecordDo
	Unscoped() IAssetLinkRecordDo
	Create(values ...*model.AssetLinkRecord) error
	CreateInBatches(values []*model.AssetLinkRecord, batchSize int) error
	Save(values ...*model.AssetLinkRecord) error
	First() (*model.AssetLinkRecord, error)
	Take() (*model.AssetLinkRecord, error)
	Last() (*model.AssetLinkRecord, error)
	Find() ([]*model.AssetLinkRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AssetLinkRecord, err error)
	FindInBatches(result *[]*model.AssetLinkRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AssetLinkRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAssetLinkRecordDo
	Assign(attrs ...field.AssignExpr) IAssetLinkRecordDo
	Joins(fields ...field.RelationField) IAssetLinkRecordDo
	Preload(fields ...field.RelationField) IAssetLinkRecordDo
	FirstOrInit() (*model.AssetLinkRecord, error)
	FirstOrCreate() (*model.AssetLinkRecord, error)
	FindByPage(offset int, limit int) (result []*model.AssetLinkRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAssetLinkRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a assetLinkRecordDo) Debug() IAssetLinkRecordDo {
	return a.withDO(a.DO.Debug())
}

func (a assetLinkRecordDo) WithContext(ctx context.Context) IAssetLinkRecordDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a assetLinkRecordDo) ReadDB() IAssetLinkRecordDo {
	return a.Clauses(dbresolver.Read)
}

func (a assetLinkRecordDo) WriteDB() IAssetLinkRecordDo {
	return a.Clauses(dbresolver.Write)
}

func (a assetLinkRecordDo) Session(config *gorm.Session) IAssetLinkRecordDo {
	return a.withDO(a.DO.Session(config))
}

func (a assetLinkRecordDo) Clauses(conds ...clause.Expression) IAssetLinkRecordDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a assetLinkRecordDo) Returning(value interface{}, columns ...string) IAssetLinkRecordDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a assetLinkRecordDo) Not(conds ...gen.Condition) IAssetLinkRecordDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a assetLinkRecordDo) Or(conds ...gen.Condition) IAssetLinkRecordDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a assetLinkRecordDo) Select(conds ...field.Expr) IAssetLinkRecordDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a assetLinkRecordDo) Where(conds ...gen.Condition) IAssetLinkRecordDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a assetLinkRecordDo) Order(conds ...field.Expr) IAssetLinkRecordDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a assetLinkRecordDo) Distinct(cols ...field.Expr) IAssetLinkRecordDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a assetLinkRecordDo) Omit(cols ...field.Expr) IAssetLinkRecordDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a assetLinkRecordDo) Join(table schema.Tabler, on ...field.Expr) IAssetLinkRecordDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a assetLinkRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAssetLinkRecordDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a assetLinkRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IAssetLinkRecordDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a assetLinkRecordDo) Group(cols ...field.Expr) IAssetLinkRecordDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a assetLinkRecordDo) Having(conds ...gen.Condition) IAssetLinkRecordDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a assetLinkRecordDo) Limit(limit int) IAssetLinkRecordDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a assetLinkRecordDo) Offset(offset int) IAssetLinkRecordDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a assetLinkRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAssetLinkRecordDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a assetLinkRecordDo) Unscoped() IAssetLinkRecordDo {
	return a.withDO(a.DO.Unscoped())
}

func (a assetLinkRecordDo) Create(values ...*model.AssetLinkRecord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a assetLinkRecordDo) CreateInBatches(values []*model.AssetLinkRecord, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a assetLinkRecordDo) Save(values ...*model.AssetLinkRecord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a assetLinkRecordDo) First() (*model.AssetLinkRecord, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetLinkRecord), nil
	}
}

func (a assetLinkRecordDo) Take() (*model.AssetLinkRecord, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetLinkRecord), nil
	}
}

func (a assetLinkRecordDo) Last() (*model.AssetLinkRecord, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetLinkRecord), nil
	}
}

func (a assetLinkRecordDo) Find() ([]*model.AssetLinkRecord, error) {
	result, err := a.DO.Find()
	return result.([]*model.AssetLinkRecord), err
}

func (a assetLinkRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AssetLinkRecord, err error) {
	buf := make([]*model.AssetLinkRecord, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a assetLinkRecordDo) FindInBatches(result *[]*model.AssetLinkRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a assetLinkRecordDo) Attrs(attrs ...field.AssignExpr) IAssetLinkRecordDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a assetLinkRecordDo) Assign(attrs ...field.AssignExpr) IAssetLinkRecordDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a assetLinkRecordDo) Joins(fields ...field.RelationField) IAssetLinkRecordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a assetLinkRecordDo) Preload(fields ...field.RelationField) IAssetLinkRecordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a assetLinkRecordDo) FirstOrInit() (*model.AssetLinkRecord, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetLinkRecord), nil
	}
}

func (a assetLinkRecordDo) FirstOrCreate() (*model.AssetLinkRecord, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetLinkRecord), nil
	}
}

func (a assetLinkRecordDo) FindByPage(offset int, limit int) (result []*model.AssetLinkRecord, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a assetLinkRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a assetLinkRecordDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a assetLinkRecordDo) Delete(models ...*model.AssetLinkRecord) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *assetLinkRecordDo) withDO(do gen.Dao) *assetLinkRecordDo {
	a.DO = *do.(*gen.DO)
	return a
}
