// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newAssetRecord(db *gorm.DB, opts ...gen.DOOption) assetRecord {
	_assetRecord := assetRecord{}

	_assetRecord.assetRecordDo.UseDB(db, opts...)
	_assetRecord.assetRecordDo.UseModel(&model.AssetRecord{})

	tableName := _assetRecord.assetRecordDo.TableName()
	_assetRecord.ALL = field.NewAsterisk(tableName)
	_assetRecord.Path = field.NewString(tableName, "path")
	_assetRecord.AssetID = field.NewString(tableName, "asset_id")
	_assetRecord.Filename = field.NewString(tableName, "filename")
	_assetRecord.Stem = field.NewString(tableName, "stem")
	_assetRecord.Extension = field.NewString(tableName, "extension")
	_assetRecord.MediaType = field.NewString(tableName, "media_type")
	_assetRecord.Size = field.NewInt64(tableName, "size")
	_assetRecord.ModifiedUnix = field.NewInt64(tableName, "modified_unix")
	_assetRecord.Width = field.NewInt(tableName, "width")
	_assetRecord.Height = field.NewInt(tableName, "height")
	_assetRecord.SHA256 = field.NewString(tableName, "sha256")
	_assetRecord.ManagedStatus = field.NewString(tableName, "managed_status")
	_assetRecord.CreatedAt = field.NewString(tableName, "created_at")
	_assetRecord.UpdatedAt = field.NewString(tableName, "updated_at")

	_assetRecord.fillFieldMap()

	return _assetRecord
}

type assetRecord struct {
	assetRecordDo

	ALL           field.Asterisk
	Path          field.String
	AssetID       field.String
	Filename      field.String
	Stem          field.String
	Extension     field.String
	MediaType     field.String
	Size          field.Int64
	ModifiedUnix  field.Int64
	Width         field.Int
	Height        field.Int
	SHA256        field.String
	ManagedStatus field.String
	CreatedAt     field.String
	UpdatedAt     field.String

	fieldMap map[string]field.Expr
}

func (a assetRecord) Table(newTableName string) *assetRecord {
	a.assetRecordDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a assetRecord) As(alias string) *assetRecord {
	a.assetRecordDo.DO = *(a.assetRecordDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *assetRecord) updateTableName(table string) *assetRecord {
	a.ALL = field.NewAsterisk(table)
	a.Path = field.NewString(table, "path")
	a.AssetID = field.NewString(table, "asset_id")
	a.Filename = field.NewString(table, "filename")
	a.Stem = field.NewString(table, "stem")
	a.Extension = field.NewString(table, "extension")
	a.MediaType = field.NewString(table, "media_type")
	a.Size = field.NewInt64(table, "size")
	a.ModifiedUnix = field.NewInt64(table, "modified_unix")
	a.Width = field.NewInt(table, "width")
	a.Height = field.NewInt(table, "height")
	a.SHA256 = field.NewString(table, "sha256")
	a.ManagedStatus = field.NewString(table, "managed_status")
	a.CreatedAt = field.NewString(table, "created_at")
	a.UpdatedAt = field.NewString(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *assetRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *assetRecord) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 14)
	a.fieldMap["path"] = a.Path
	a.fieldMap["asset_id"] = a.AssetID
	a.fieldMap["filename"] = a.Filename
	a.fieldMap["stem"] = a.Stem
	a.fieldMap["extension"] = a.Extension
	a.fieldMap["media_type"] = a.MediaType
	a.fieldMap["size"] = a.Size
	a.fieldMap["modified_unix"] = a.ModifiedUnix
	a.fieldMap["width"] = a.Width
	a.fieldMap["height"] = a.Height
	a.fieldMap["sha256"] = a.SHA256
	a.fieldMap["managed_status"] = a.ManagedStatus
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a assetRecord) clone(db *gorm.DB) assetRecord {
	a.assetRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a assetRecord) replaceDB(db *gorm.DB) assetRecord {
	a.assetRecordDo.ReplaceDB(db)
	return a
}

type assetRecordDo struct{ gen.DO }

type IAssetRecordDo interface {
	gen.SubQuery
	Debug() IAssetRecordDo
	WithContext(ctx context.Context) IAssetRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAssetRecordDo
	WriteDB() IAssetRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAssetRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAssetRecordDo
	Not(conds ...gen.Condition) IAssetRecordDo
	Or(conds ...gen.Condition) IAssetRecordDo
	Select(conds ...field.Expr) IAssetRecordDo
	Where(conds ...gen.Condition) IAssetRecordDo
	Order(conds ...field.Expr) IAssetRecordDo
	Distinct(cols ...field.Expr) IAssetRecordDo
	Omit(cols ...field.Expr) IAssetRecordDo
	Join(table schema.Tabler, on ...field.Expr) IAssetRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAssetRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAssetRecordDo
	Group(cols ...field.Expr) IAssetRecordDo
	Having(conds ...gen.Condition) IAssetRecordDo
	Limit(limit int) IAssetRecordDo
	Offset(offset int) IAssetRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAssetRecordDo
	Unscoped() IAssetRecordDo
	Create(values ...*model.AssetRecord) error
	CreateInBatches(values []*model.AssetRecord, batchSize int) error
	Save(values ...*model.AssetRecord) error
	First() (*model.AssetRecord, error)
	Take() (*model.AssetRecord, error)
	Last() (*model.AssetRecord, error)
	Find() ([]*model.AssetRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AssetRecord, err error)
	FindInBatches(result *[]*model.AssetRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AssetRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAssetRecordDo
	Assign(attrs ...field.AssignExpr) IAssetRecordDo
	Joins(fields ...field.RelationField) IAssetRecordDo
	Preload(fields ...field.RelationField) IAssetRecordDo
	FirstOrInit() (*model.AssetRecord, error)
	FirstOrCreate() (*model.AssetRecord, error)
	FindByPage(offset int, limit int) (result []*model.AssetRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAssetRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a assetRecordDo) Debug() IAssetRecordDo {
	return a.withDO(a.DO.Debug())
}

func (a assetRecordDo) WithContext(ctx context.Context) IAssetRecordDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a assetRecordDo) ReadDB() IAssetRecordDo {
	return a.Clauses(dbresolver.Read)
}

func (a assetRecordDo) WriteDB() IAssetRecordDo {
	return a.Clauses(dbresolver.Write)
}

func (a assetRecordDo) Session(config *gorm.Session) IAssetRecordDo {
	return a.withDO(a.DO.Session(config))
}

func (a assetRecordDo) Clauses(conds ...clause.Expression) IAssetRecordDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a assetRecordDo) Returning(value interface{}, columns ...string) IAssetRecordDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a assetRecordDo) Not(conds ...gen.Condition) IAssetRecordDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a assetRecordDo) Or(conds ...gen.Condition) IAssetRecordDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a assetRecordDo) Select(conds ...field.Expr) IAssetRecordDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a assetRecordDo) Where(conds ...gen.Condition) IAssetRecordDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a assetRecordDo) Order(conds ...field.Expr) IAssetRecordDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a assetRecordDo) Distinct(cols ...field.Expr) IAssetRecordDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a assetRecordDo) Omit(cols ...field.Expr) IAssetRecordDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a assetRecordDo) Join(table schema.Tabler, on ...field.Expr) IAssetRecordDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a assetRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAssetRecordDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a assetRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IAssetRecordDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a assetRecordDo) Group(cols ...field.Expr) IAssetRecordDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a assetRecordDo) Having(conds ...gen.Condition) IAssetRecordDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a assetRecordDo) Limit(limit int) IAssetRecordDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a assetRecordDo) Offset(offset int) IAssetRecordDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a assetRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAssetRecordDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a assetRecordDo) Unscoped() IAssetRecordDo {
	return a.withDO(a.DO.Unscoped())
}

func (a assetRecordDo) Create(values ...*model.AssetRecord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a assetRecordDo) CreateInBatches(values []*model.AssetRecord, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a assetRecordDo) Save(values ...*model.AssetRecord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a assetRecordDo) First() (*model.AssetRecord, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetRecord), nil
	}
}

func (a assetRecordDo) Take() (*model.AssetRecord, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetRecord), nil
	}
}

func (a assetRecordDo) Last() (*model.AssetRecord, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetRecord), nil
	}
}

func (a assetRecordDo) Find() ([]*model.AssetRecord, error) {
	result, err := a.DO.Find()
	return result.([]*model.AssetRecord), err
}

func (a assetRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AssetRecord, err error) {
	buf := make([]*model.AssetRecord, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a assetRecordDo) FindInBatches(result *[]*model.AssetRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a assetRecordDo) Attrs(attrs ...field.AssignExpr) IAssetRecordDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a assetRecordDo) Assign(attrs ...field.AssignExpr) IAssetRecordDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a assetRecordDo) Joins(fields ...field.RelationField) IAssetRecordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a assetRecordDo) Preload(fields ...field.RelationField) IAssetRecordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a assetRecordDo) FirstOrInit() (*model.AssetRecord, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetRecord), nil
	}
}

func (a assetRecordDo) FirstOrCreate() (*model.AssetRecord, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetRecord), nil
	}
}

func (a assetRecordDo) FindByPage(offset int, limit int) (result []*model.AssetRecord, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a assetRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a assetRecordDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a assetRecordDo) Delete(models ...*model.AssetRecord) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *assetRecordDo) withDO(do gen.Dao) *assetRecordDo {
	a.DO = *do.(*gen.DO)
	return a
}
