// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newAttachmentRecord(db *gorm.DB, opts ...gen.DOOption) attachmentRecord {
	_attachmentRecord := attachmentRecord{}

	_attachmentRecord.attachmentRecordDo.UseDB(db, opts...)
	_attachmentRecord.attachmentRecordDo.UseModel(&model.AttachmentRecord{})

	tableName := _attachmentRecord.attachmentRecordDo.TableName()
	_attachmentRecord.ALL = field.NewAsterisk(tableName)
	_attachmentRecord.ID = field.NewUint(tableName, "id")
	_attachmentRecord.NotePath = field.NewString(tableName, "note_path")
	_attachmentRecord.ReferenceText = field.NewString(tableName, "reference_text")
	_attachmentRecord.TargetPath = field.NewString(tableName, "target_path")
	_attachmentRecord.MediaType = field.NewString(tableName, "media_type")
	_attachmentRecord.Exists = field.NewBool(tableName, "exists")

	_attachmentRecord.fillFieldMap()

	return _attachmentRecord
}

type attachmentRecord struct {
	attachmentRecordDo

	ALL           field.Asterisk
	ID            field.Uint
	NotePath      field.String
	ReferenceText field.String
	TargetPath    field.String
	MediaType     field.String
	Exists        field.Bool

	fieldMap map[string]field.Expr
}

func (a attachmentRecord) Table(newTableName string) *attachmentRecord {
	a.attachmentRecordDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a attachmentRecord) As(alias string) *attachmentRecord {
	a.attachmentRecordDo.DO = *(a.attachmentRecordDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *attachmentRecord) updateTableName(table string) *attachmentRecord {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint(table, "id")
	a.NotePath = field.NewString(table, "note_path")
	a.ReferenceText = field.NewString(table, "reference_text")
	a.TargetPath = field.NewString(table, "target_path")
	a.MediaType = field.NewString(table, "media_type")
	a.Exists = field.NewBool(table, "exists")

	a.fillFieldMap()

	return a
}

func (a *attachmentRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *attachmentRecord) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.ID
	a.fieldMap["note_path"] = a.NotePath
	a.fieldMap["reference_text"] = a.ReferenceText
	a.fieldMap["target_path"] = a.TargetPath
	a.fieldMap["media_type"] = a.MediaType
	a.fieldMap["exists"] = a.Exists
}

func (a attachmentRecord) clone(db *gorm.DB) attachmentRecord {
	a.attachmentRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a attachmentRecord) replaceDB(db *gorm.DB) attachmentRecord {
	a.attachmentRecordDo.ReplaceDB(db)
	return a
}

type attachmentRecordDo struct{ gen.DO }

type IAttachmentRecordDo interface {
	gen.SubQuery
	Debug() IAttachmentRecordDo
	WithContext(ctx context.Context) IAttachmentRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAttachmentRecordDo
	WriteDB() IAttachmentRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAttachmentRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAttachmentRecordDo
	Not(conds ...gen.Condition) IAttachmentRecordDo
	Or(conds ...gen.Condition) IAttachmentRecordDo
	Select(conds ...field.Expr) IAttachmentRecordDo
	Where(conds ...gen.Condition) IAttachmentRecordDo
	Order(conds ...field.Expr) IAttachmentRecordDo
	Distinct(cols ...field.Expr) IAttachmentRecordDo
	Omit(cols ...field.Expr) IAttachmentRecordDo
	Join(table schema.Tabler, on ...field.Expr) IAttachmentRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAttachmentRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAttachmentRecordDo
	Group(cols ...field.Expr) IAttachmentRecordDo
	Having(conds ...gen.Condition) IAttachmentRecordDo
	Limit(limit int) IAttachmentRecordDo
	Offset(offset int) IAttachmentRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAttachmentRecordDo
	Unscoped() IAttachmentRecordDo
	Create(values ...*model.AttachmentRecord) error
	CreateInBatches(values []*model.AttachmentRecord, batchSize int) error
	Save(values ...*model.AttachmentRecord) error
	First() (*model.AttachmentRecord, error)
	Take() (*model.AttachmentRecord, error)
	Last() (*model.AttachmentRecord, error)
	Find() ([]*model.AttachmentRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AttachmentRecord, err error)
	FindInBatches(result *[]*model.AttachmentRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AttachmentRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAttachmentRecordDo
	Assign(attrs ...field.AssignExpr) IAttachmentRecordDo
	Joins(fields ...field.RelationField) IAttachmentRecordDo
	Preload(fields ...field.RelationField) IAttachmentRecordDo
	FirstOrInit() (*model.AttachmentRecord, error)
	FirstOrCreate() (*model.AttachmentRecord, error)
	FindByPage(offset int, limit int) (result []*model.AttachmentRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAttachmentRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a attachmentRecordDo) Debug() IAttachmentRecordDo {
	return a.withDO(a.DO.Debug())
}

func (a attachmentRecordDo) WithContext(ctx context.Context) IAttachmentRecordDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a attachmentRecordDo) ReadDB() IAttachmentRecordDo {
	return a.Clauses(dbresolver.Read)
}

func (a attachmentRecordDo) WriteDB() IAttachmentRecordDo {
	return a.Clauses(dbresolver.Write)
}

func (a attachmentRecordDo) Session(config *gorm.Session) IAttachmentRecordDo {
	return a.withDO(a.DO.Session(config))
}

func (a attachmentRecordDo) Clauses(conds ...clause.Expression) IAttachmentRecordDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a attachmentRecordDo) Returning(value interface{}, columns ...string) IAttachmentRecordDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a attachmentRecordDo) Not(conds ...gen.Condition) IAttachmentRecordDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a attachmentRecordDo) Or(conds ...gen.Condition) IAttachmentRecordDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a attachmentRecordDo) Select(conds ...field.Expr) IAttachmentRecordDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a attachmentRecordDo) Where(conds ...gen.Condition) IAttachmentRecordDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a attachmentRecordDo) Order(conds ...field.Expr) IAttachmentRecordDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a attachmentRecordDo) Distinct(cols ...field.Expr) IAttachmentRecordDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a attachmentRecordDo) Omit(cols ...field.Expr) IAttachmentRecordDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a attachmentRecordDo) Join(table schema.Tabler, on ...field.Expr) IAttachmentRecordDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a attachmentRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAttachmentRecordDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a attachmentRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IAttachmentRecordDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a attachmentRecordDo) Group(cols ...field.Expr) IAttachmentRecordDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a attachmentRecordDo) Having(conds ...gen.Condition) IAttachmentRecordDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a attachmentRecordDo) Limit(limit int) IAttachmentRecordDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a attachmentRecordDo) Offset(offset int) IAttachmentRecordDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a attachmentRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAttachmentRecordDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a attachmentRecordDo) Unscoped() IAttachmentRecordDo {
	return a.withDO(a.DO.Unscoped())
}

func (a attachmentRecordDo) Create(values ...*model.AttachmentRecord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a attachmentRecordDo) CreateInBatches(values []*model.AttachmentRecord, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a attachmentRecordDo) Save(values ...*model.AttachmentRecord) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a attachmentRecordDo) First() (*model.AttachmentRecord, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AttachmentRecord), nil
	}
}

func (a attachmentRecordDo) Take() (*model.AttachmentRecord, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AttachmentRecord), nil
	}
}

func (a attachmentRecordDo) Last() (*model.AttachmentRecord, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AttachmentRecord), nil
	}
}

func (a attachmentRecordDo) Find() ([]*model.AttachmentRecord, error) {
	result, err := a.DO.Find()
	return result.([]*model.AttachmentRecord), err
}

func (a attachmentRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AttachmentRecord, err error) {
	buf := make([]*model.AttachmentRecord, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a attachmentRecordDo) FindInBatches(result *[]*model.AttachmentRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a attachmentRecordDo) Attrs(attrs ...field.AssignExpr) IAttachmentRecordDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a attachmentRecordDo) Assign(attrs ...field.AssignExpr) IAttachmentRecordDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a attachmentRecordDo) Joins(fields ...field.RelationField) IAttachmentRecordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a attachmentRecordDo) Preload(fields ...field.RelationField) IAttachmentRecordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a attachmentRecordDo) FirstOrInit() (*model.AttachmentRecord, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AttachmentRecord), nil
	}
}

func (a attachmentRecordDo) FirstOrCreate() (*model.AttachmentRecord, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AttachmentRecord), nil
	}
}

func (a attachmentRecordDo) FindByPage(offset int, limit int) (result []*model.AttachmentRecord, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a attachmentRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a attachmentRecordDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a attachmentRecordDo) Delete(models ...*model.AttachmentRecord) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *attachmentRecordDo) withDO(do gen.Dao) *attachmentRecordDo {
	a.DO = *do.(*gen.DO)
	return a
}
