// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newDimensionCountRecord(db *gorm.DB, opts ...gen.DOOption) dimensionCountRecord {
	_dimensionCountRecord := dimensionCountRecord{}

	_dimensionCountRecord.dimensionCountRecordDo.UseDB(db, opts...)
	_dimensionCountRecord.dimensionCountRecordDo.UseModel(&model.DimensionCountRecord{})

	tableName := _dimensionCountRecord.dimensionCountRecordDo.TableName()
	_dimensionCountRecord.ALL = field.NewAsterisk(tableName)
	_dimensionCountRecord.ID = field.NewUint(tableName, "id")
	_dimensionCountRecord.Dimension = field.NewString(tableName, "dimension")
	_dimensionCountRecord.Value = field.NewString(tableName, "value")
	_dimensionCountRecord.Count_ = field.NewInt(tableName, "count")

	_dimensionCountRecord.fillFieldMap()

	return _dimensionCountRecord
}

type dimensionCountRecord struct {
	dimensionCountRecordDo

	ALL       field.Asterisk
	ID        field.Uint
	Dimension field.String
	Value     field.String
	Count_    field.Int

	fieldMap map[string]field.Expr
}

func (d dimensionCountRecord) Table(newTableName string) *dimensionCountRecord {
	d.dimensionCountRecordDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dimensionCountRecord) As(alias string) *dimensionCountRecord {
	d.dimensionCountRecordDo.DO = *(d.dimensionCountRecordDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dimensionCountRecord) updateTableName(table string) *dimensionCountRecord {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint(table, "id")
	d.Dimension = field.NewString(table, "dimension")
	d.Value = field.NewString(table, "value")
	d.Count_ = field.NewInt(table, "count")

	d.fillFieldMap()

	return d
}

func (d *dimensionCountRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dimensionCountRecord) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 4)
	d.fieldMap["id"] = d.ID
	d.fieldMap["dimension"] = d.Dimension
	d.fieldMap["value"] = d.Value
	d.fieldMap["count"] = d.Count_
}

func (d dimensionCountRecord) clone(db *gorm.DB) dimensionCountRecord {
	d.dimensionCountRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dimensionCountRecord) replaceDB(db *gorm.DB) dimensionCountRecord {
	d.dimensionCountRecordDo.ReplaceDB(db)
	return d
}

type dimensionCountRecordDo struct{ gen.DO }

type IDimensionCountRecordDo interface {
	gen.SubQuery
	Debug() IDimensionCountRecordDo
	WithContext(ctx context.Context) IDimensionCountRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDimensionCountRecordDo
	WriteDB() IDimensionCountRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDimensionCountRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDimensionCountRecordDo
	Not(conds ...gen.Condition) IDimensionCountRecordDo
	Or(conds ...gen.Condition) IDimensionCountRecordDo
	Select(conds ...field.Expr) IDimensionCountRecordDo
	Where(conds ...gen.Condition) IDimensionCountRecordDo
	Order(conds ...field.Expr) IDimensionCountRecordDo
	Distinct(cols ...field.Expr) IDimensionCountRecordDo
	Omit(cols ...field.Expr) IDimensionCountRecordDo
	Join(table schema.Tabler, on ...field.Expr) IDimensionCountRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDimensionCountRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDimensionCountRecordDo
	Group(cols ...field.Expr) IDimensionCountRecordDo
	Having(conds ...gen.Condition) IDimensionCountRecordDo
	Limit(limit int) IDimensionCountRecordDo
	Offset(offset int) IDimensionCountRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDimensionCountRecordDo
	Unscoped() IDimensionCountRecordDo
	Create(values ...*model.DimensionCountRecord) error
	CreateInBatches(values []*model.DimensionCountRecord, batchSize int) error
	Save(values ...*model.DimensionCountRecord) error
	First() (*model.DimensionCountRecord, error)
	Take() (*model.DimensionCountRecord, error)
	Last() (*model.DimensionCountRecord, error)
	Find() ([]*model.DimensionCountRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DimensionCountRecord, err error)
	FindInBatches(result *[]*model.DimensionCountRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DimensionCountRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDimensionCountRecordDo
	Assign(attrs ...field.AssignExpr) IDimensionCountRecordDo
	Joins(fields ...field.RelationField) IDimensionCountRecordDo
	Preload(fields ...field.RelationField) IDimensionCountRecordDo
	FirstOrInit() (*model.DimensionCountRecord, error)
	FirstOrCreate() (*model.DimensionCountRecord, error)
	FindByPage(offset int, limit int) (result []*model.DimensionCountRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDimensionCountRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dimensionCountRecordDo) Debug() IDimensionCountRecordDo {
	return d.withDO(d.DO.Debug())
}

func (d dimensionCountRecordDo) WithContext(ctx context.Context) IDimensionCountRecordDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dimensionCountRecordDo) ReadDB() IDimensionCountRecordDo {
	return d.Clauses(dbresolver.Read)
}

func (d dimensionCountRecordDo) WriteDB() IDimensionCountRecordDo {
	return d.Clauses(dbresolver.Write)
}

func (d dimensionCountRecordDo) Session(config *gorm.Session) IDimensionCountRecordDo {
	return d.withDO(d.DO.Session(config))
}

func (d dimensionCountRecordDo) Clauses(conds ...clause.Expression) IDimensionCountRecordDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dimensionCountRecordDo) Returning(value interface{}, columns ...string) IDimensionCountRecordDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dimensionCountRecordDo) Not(conds ...gen.Condition) IDimensionCountRecordDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dimensionCountRecordDo) Or(conds ...gen.Condition) IDimensionCountRecordDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dimensionCountRecordDo) Select(conds ...field.Expr) IDimensionCountRecordDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dimensionCountRecordDo) Where(conds ...gen.Condition) IDimensionCountRecordDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dimensionCountRecordDo) Order(conds ...field.Expr) IDimensionCountRecordDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dimensionCountRecordDo) Distinct(cols ...field.Expr) IDimensionCountRecordDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dimensionCountRecordDo) Omit(cols ...field.Expr) IDimensionCountRecordDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dimensionCountRecordDo) Join(table schema.Tabler, on ...field.Expr) IDimensionCountRecordDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dimensionCountRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDimensionCountRecordDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dimensionCountRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IDimensionCountRecordDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dimensionCountRecordDo) Group(cols ...field.Expr) IDimensionCountRecordDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dimensionCountRecordDo) Having(conds ...gen.Condition) IDimensionCountRecordDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dimensionCountRecordDo) Limit(limit int) IDimensionCountRecordDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dimensionCountRecordDo) Offset(offset int) IDimensionCountRecordDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dimensionCountRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDimensionCountRecordDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dimensionCountRecordDo) Unscoped() IDimensionCountRecordDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dimensionCountRecordDo) Create(values ...*model.DimensionCountRecord) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dimensionCountRecordDo) CreateInBatches(values []*model.DimensionCountRecord, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dimensionCountRecordDo) Save(values ...*model.DimensionCountRecord) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dimensionCountRecordDo) First() (*model.DimensionCountRecord, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DimensionCountRecord), nil
	}
}

func (d dimensionCountRecordDo) Take() (*model.DimensionCountRecord, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DimensionCountRecord), nil
	}
}

func (d dimensionCountRecordDo) Last() (*model.DimensionCountRecord, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DimensionCountRecord), nil
	}
}

func (d dimensionCountRecordDo) Find() ([]*model.DimensionCountRecord, error) {
	result, err := d.DO.Find()
	return result.([]*model.DimensionCountRecord), err
}

func (d dimensionCountRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DimensionCountRecord, err error) {
	buf := make([]*model.DimensionCountRecord, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dimensionCountRecordDo) FindInBatches(result *[]*model.DimensionCountRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dimensionCountRecordDo) Attrs(attrs ...field.AssignExpr) IDimensionCountRecordDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dimensionCountRecordDo) Assign(attrs ...field.AssignExpr) IDimensionCountRecordDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dimensionCountRecordDo) Joins(fields ...field.RelationField) IDimensionCountRecordDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dimensionCountRecordDo) Preload(fields ...field.RelationField) IDimensionCountRecordDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dimensionCountRecordDo) FirstOrInit() (*model.DimensionCountRecord, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DimensionCountRecord), nil
	}
}

func (d dimensionCountRecordDo) FirstOrCreate() (*model.DimensionCountRecord, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DimensionCountRecord), nil
	}
}

func (d dimensionCountRecordDo) FindByPage(offset int, limit int) (result []*model.DimensionCountRecord, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dimensionCountRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dimensionCountRecordDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dimensionCountRecordDo) Delete(models ...*model.DimensionCountRecord) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dimensionCountRecordDo) withDO(do gen.Dao) *dimensionCountRecordDo {
	d.DO = *do.(*gen.DO)
	return d
}
