// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newFolderRecord(db *gorm.DB, opts ...gen.DOOption) folderRecord {
	_folderRecord := folderRecord{}

	_folderRecord.folderRecordDo.UseDB(db, opts...)
	_folderRecord.folderRecordDo.UseModel(&model.FolderRecord{})

	tableName := _folderRecord.folderRecordDo.TableName()
	_folderRecord.ALL = field.NewAsterisk(tableName)
	_folderRecord.Path = field.NewString(tableName, "path")
	_folderRecord.Purpose = field.NewString(tableName, "purpose")
	_folderRecord.ManagedStatus = field.NewString(tableName, "managed_status")
	_folderRecord.Exists = field.NewBool(tableName, "exists")
	_folderRecord.Empty = field.NewBool(tableName, "empty")
	_folderRecord.Depth = field.NewInt(tableName, "depth")
	_folderRecord.NoteCount = field.NewInt(tableName, "note_count")
	_folderRecord.AssetCount = field.NewInt(tableName, "asset_count")
	_folderRecord.CreatedAt = field.NewString(tableName, "created_at")
	_folderRecord.UpdatedAt = field.NewString(tableName, "updated_at")

	_folderRecord.fillFieldMap()

	return _folderRecord
}

type folderRecord struct {
	folderRecordDo

	ALL           field.Asterisk
	Path          field.String
	Purpose       field.String
	ManagedStatus field.String
	Exists        field.Bool
	Empty         field.Bool
	Depth         field.Int
	NoteCount     field.Int
	AssetCount    field.Int
	CreatedAt     field.String
	UpdatedAt     field.String

	fieldMap map[string]field.Expr
}

func (f folderRecord) Table(newTableName string) *folderRecord {
	f.folderRecordDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f folderRecord) As(alias string) *folderRecord {
	f.folderRecordDo.DO = *(f.folderRecordDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *folderRecord) updateTableName(table string) *folderRecord {
	f.ALL = field.NewAsterisk(table)
	f.Path = field.NewString(table, "path")
	f.Purpose = field.NewString(table, "purpose")
	f.ManagedStatus = field.NewString(table, "managed_status")
	f.Exists = field.NewBool(table, "exists")
	f.Empty = field.NewBool(table, "empty")
	f.Depth = field.NewInt(table, "depth")
	f.NoteCount = field.NewInt(table, "note_count")
	f.AssetCount = field.NewInt(table, "asset_count")
	f.CreatedAt = field.NewString(table, "created_at")
	f.UpdatedAt = field.NewString(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *folderRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *folderRecord) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 10)
	f.fieldMap["path"] = f.Path
	f.fieldMap["purpose"] = f.Purpose
	f.fieldMap["managed_status"] = f.ManagedStatus
	f.fieldMap["exists"] = f.Exists
	f.fieldMap["empty"] = f.Empty
	f.fieldMap["depth"] = f.Depth
	f.fieldMap["note_count"] = f.NoteCount
	f.fieldMap["asset_count"] = f.AssetCount
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f folderRecord) clone(db *gorm.DB) folderRecord {
	f.folderRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f folderRecord) replaceDB(db *gorm.DB) folderRecord {
	f.folderRecordDo.ReplaceDB(db)
	return f
}

type folderRecordDo struct{ gen.DO }

type IFolderRecordDo interface {
	gen.SubQuery
	Debug() IFolderRecordDo
	WithContext(ctx context.Context) IFolderRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFolderRecordDo
	WriteDB() IFolderRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFolderRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFolderRecordDo
	Not(conds ...gen.Condition) IFolderRecordDo
	Or(conds ...gen.Condition) IFolderRecordDo
	Select(conds ...field.Expr) IFolderRecordDo
	Where(conds ...gen.Condition) IFolderRecordDo
	Order(conds ...field.Expr) IFolderRecordDo
	Distinct(cols ...field.Expr) IFolderRecordDo
	Omit(cols ...field.Expr) IFolderRecordDo
	Join(table schema.Tabler, on ...field.Expr) IFolderRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFolderRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFolderRecordDo
	Group(cols ...field.Expr) IFolderRecordDo
	Having(conds ...gen.Condition) IFolderRecordDo
	Limit(limit int) IFolderRecordDo
	Offset(offset int) IFolderRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFolderRecordDo
	Unscoped() IFolderRecordDo
	Create(values ...*model.FolderRecord) error
	CreateInBatches(values []*model.FolderRecord, batchSize int) error
	Save(values ...*model.FolderRecord) error
	First() (*model.FolderRecord, error)
	Take() (*model.FolderRecord, error)
	Last() (*model.FolderRecord, error)
	Find() ([]*model.FolderRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FolderRecord, err error)
	FindInBatches(result *[]*model.FolderRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FolderRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFolderRecordDo
	Assign(attrs ...field.AssignExpr) IFolderRecordDo
	Joins(fields ...field.RelationField) IFolderRecordDo
	Preload(fields ...field.RelationField) IFolderRecordDo
	FirstOrInit() (*model.FolderRecord, error)
	FirstOrCreate() (*model.FolderRecord, error)
	FindByPage(offset int, limit int) (result []*model.FolderRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFolderRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f folderRecordDo) Debug() IFolderRecordDo {
	return f.withDO(f.DO.Debug())
}

func (f folderRecordDo) WithContext(ctx context.Context) IFolderRecordDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f folderRecordDo) ReadDB() IFolderRecordDo {
	return f.Clauses(dbresolver.Read)
}

func (f folderRecordDo) WriteDB() IFolderRecordDo {
	return f.Clauses(dbresolver.Write)
}

func (f folderRecordDo) Session(config *gorm.Session) IFolderRecordDo {
	return f.withDO(f.DO.Session(config))
}

func (f folderRecordDo) Clauses(conds ...clause.Expression) IFolderRecordDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f folderRecordDo) Returning(value interface{}, columns ...string) IFolderRecordDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f folderRecordDo) Not(conds ...gen.Condition) IFolderRecordDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f folderRecordDo) Or(conds ...gen.Condition) IFolderRecordDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f folderRecordDo) Select(conds ...field.Expr) IFolderRecordDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f folderRecordDo) Where(conds ...gen.Condition) IFolderRecordDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f folderRecordDo) Order(conds ...field.Expr) IFolderRecordDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f folderRecordDo) Distinct(cols ...field.Expr) IFolderRecordDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f folderRecordDo) Omit(cols ...field.Expr) IFolderRecordDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f folderRecordDo) Join(table schema.Tabler, on ...field.Expr) IFolderRecordDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f folderRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFolderRecordDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f folderRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IFolderRecordDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f folderRecordDo) Group(cols ...field.Expr) IFolderRecordDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f folderRecordDo) Having(conds ...gen.Condition) IFolderRecordDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f folderRecordDo) Limit(limit int) IFolderRecordDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f folderRecordDo) Offset(offset int) IFolderRecordDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f folderRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFolderRecordDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f folderRecordDo) Unscoped() IFolderRecordDo {
	return f.withDO(f.DO.Unscoped())
}

func (f folderRecordDo) Create(values ...*model.FolderRecord) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f folderRecordDo) CreateInBatches(values []*model.FolderRecord, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f folderRecordDo) Save(values ...*model.FolderRecord) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f folderRecordDo) First() (*model.FolderRecord, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FolderRecord), nil
	}
}

func (f folderRecordDo) Take() (*model.FolderRecord, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FolderRecord), nil
	}
}

func (f folderRecordDo) Last() (*model.FolderRecord, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FolderRecord), nil
	}
}

func (f folderRecordDo) Find() ([]*model.FolderRecord, error) {
	result, err := f.DO.Find()
	return result.([]*model.FolderRecord), err
}

func (f folderRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FolderRecord, err error) {
	buf := make([]*model.FolderRecord, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f folderRecordDo) FindInBatches(result *[]*model.FolderRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f folderRecordDo) Attrs(attrs ...field.AssignExpr) IFolderRecordDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f folderRecordDo) Assign(attrs ...field.AssignExpr) IFolderRecordDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f folderRecordDo) Joins(fields ...field.RelationField) IFolderRecordDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f folderRecordDo) Preload(fields ...field.RelationField) IFolderRecordDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f folderRecordDo) FirstOrInit() (*model.FolderRecord, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FolderRecord), nil
	}
}

func (f folderRecordDo) FirstOrCreate() (*model.FolderRecord, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FolderRecord), nil
	}
}

func (f folderRecordDo) FindByPage(offset int, limit int) (result []*model.FolderRecord, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f folderRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f folderRecordDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f folderRecordDo) Delete(models ...*model.FolderRecord) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *folderRecordDo) withDO(do gen.Dao) *folderRecordDo {
	f.DO = *do.(*gen.DO)
	return f
}
