// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                          = new(Query)
	AssetLinkRecord            *assetLinkRecord
	AssetRecord                *assetRecord
	AttachmentRecord           *attachmentRecord
	DimensionCountRecord       *dimensionCountRecord
	FolderRecord               *folderRecord
	IndexMetaRecord            *indexMetaRecord
	LinkRecord                 *linkRecord
	NoteRecord                 *noteRecord
	NoteTextRecord             *noteTextRecord
	PromptAssetRecord          *promptAssetRecord
	PromptAssetSourceRefRecord *promptAssetSourceRefRecord
	PromptAssetVersionRecord   *promptAssetVersionRecord
	PromptUsageFeedbackRecord  *promptUsageFeedbackRecord
	PropertyDefinitionRecord   *propertyDefinitionRecord
	PropertyValueRecord        *propertyValueRecord
	SearchTokenRecord          *searchTokenRecord
	TagRecord                  *tagRecord
	TaskRecord                 *taskRecord
	VaultFileRecord            *vaultFileRecord
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AssetLinkRecord = &Q.AssetLinkRecord
	AssetRecord = &Q.AssetRecord
	AttachmentRecord = &Q.AttachmentRecord
	DimensionCountRecord = &Q.DimensionCountRecord
	FolderRecord = &Q.FolderRecord
	IndexMetaRecord = &Q.IndexMetaRecord
	LinkRecord = &Q.LinkRecord
	NoteRecord = &Q.NoteRecord
	NoteTextRecord = &Q.NoteTextRecord
	PromptAssetRecord = &Q.PromptAssetRecord
	PromptAssetSourceRefRecord = &Q.PromptAssetSourceRefRecord
	PromptAssetVersionRecord = &Q.PromptAssetVersionRecord
	PromptUsageFeedbackRecord = &Q.PromptUsageFeedbackRecord
	PropertyDefinitionRecord = &Q.PropertyDefinitionRecord
	PropertyValueRecord = &Q.PropertyValueRecord
	SearchTokenRecord = &Q.SearchTokenRecord
	TagRecord = &Q.TagRecord
	TaskRecord = &Q.TaskRecord
	VaultFileRecord = &Q.VaultFileRecord
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                         db,
		AssetLinkRecord:            newAssetLinkRecord(db, opts...),
		AssetRecord:                newAssetRecord(db, opts...),
		AttachmentRecord:           newAttachmentRecord(db, opts...),
		DimensionCountRecord:       newDimensionCountRecord(db, opts...),
		FolderRecord:               newFolderRecord(db, opts...),
		IndexMetaRecord:            newIndexMetaRecord(db, opts...),
		LinkRecord:                 newLinkRecord(db, opts...),
		NoteRecord:                 newNoteRecord(db, opts...),
		NoteTextRecord:             newNoteTextRecord(db, opts...),
		PromptAssetRecord:          newPromptAssetRecord(db, opts...),
		PromptAssetSourceRefRecord: newPromptAssetSourceRefRecord(db, opts...),
		PromptAssetVersionRecord:   newPromptAssetVersionRecord(db, opts...),
		PromptUsageFeedbackRecord:  newPromptUsageFeedbackRecord(db, opts...),
		PropertyDefinitionRecord:   newPropertyDefinitionRecord(db, opts...),
		PropertyValueRecord:        newPropertyValueRecord(db, opts...),
		SearchTokenRecord:          newSearchTokenRecord(db, opts...),
		TagRecord:                  newTagRecord(db, opts...),
		TaskRecord:                 newTaskRecord(db, opts...),
		VaultFileRecord:            newVaultFileRecord(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AssetLinkRecord            assetLinkRecord
	AssetRecord                assetRecord
	AttachmentRecord           attachmentRecord
	DimensionCountRecord       dimensionCountRecord
	FolderRecord               folderRecord
	IndexMetaRecord            indexMetaRecord
	LinkRecord                 linkRecord
	NoteRecord                 noteRecord
	NoteTextRecord             noteTextRecord
	PromptAssetRecord          promptAssetRecord
	PromptAssetSourceRefRecord promptAssetSourceRefRecord
	PromptAssetVersionRecord   promptAssetVersionRecord
	PromptUsageFeedbackRecord  promptUsageFeedbackRecord
	PropertyDefinitionRecord   propertyDefinitionRecord
	PropertyValueRecord        propertyValueRecord
	SearchTokenRecord          searchTokenRecord
	TagRecord                  tagRecord
	TaskRecord                 taskRecord
	VaultFileRecord            vaultFileRecord
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                         db,
		AssetLinkRecord:            q.AssetLinkRecord.clone(db),
		AssetRecord:                q.AssetRecord.clone(db),
		AttachmentRecord:           q.AttachmentRecord.clone(db),
		DimensionCountRecord:       q.DimensionCountRecord.clone(db),
		FolderRecord:               q.FolderRecord.clone(db),
		IndexMetaRecord:            q.IndexMetaRecord.clone(db),
		LinkRecord:                 q.LinkRecord.clone(db),
		NoteRecord:                 q.NoteRecord.clone(db),
		NoteTextRecord:             q.NoteTextRecord.clone(db),
		PromptAssetRecord:          q.PromptAssetRecord.clone(db),
		PromptAssetSourceRefRecord: q.PromptAssetSourceRefRecord.clone(db),
		PromptAssetVersionRecord:   q.PromptAssetVersionRecord.clone(db),
		PromptUsageFeedbackRecord:  q.PromptUsageFeedbackRecord.clone(db),
		PropertyDefinitionRecord:   q.PropertyDefinitionRecord.clone(db),
		PropertyValueRecord:        q.PropertyValueRecord.clone(db),
		SearchTokenRecord:          q.SearchTokenRecord.clone(db),
		TagRecord:                  q.TagRecord.clone(db),
		TaskRecord:                 q.TaskRecord.clone(db),
		VaultFileRecord:            q.VaultFileRecord.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                         db,
		AssetLinkRecord:            q.AssetLinkRecord.replaceDB(db),
		AssetRecord:                q.AssetRecord.replaceDB(db),
		AttachmentRecord:           q.AttachmentRecord.replaceDB(db),
		DimensionCountRecord:       q.DimensionCountRecord.replaceDB(db),
		FolderRecord:               q.FolderRecord.replaceDB(db),
		IndexMetaRecord:            q.IndexMetaRecord.replaceDB(db),
		LinkRecord:                 q.LinkRecord.replaceDB(db),
		NoteRecord:                 q.NoteRecord.replaceDB(db),
		NoteTextRecord:             q.NoteTextRecord.replaceDB(db),
		PromptAssetRecord:          q.PromptAssetRecord.replaceDB(db),
		PromptAssetSourceRefRecord: q.PromptAssetSourceRefRecord.replaceDB(db),
		PromptAssetVersionRecord:   q.PromptAssetVersionRecord.replaceDB(db),
		PromptUsageFeedbackRecord:  q.PromptUsageFeedbackRecord.replaceDB(db),
		PropertyDefinitionRecord:   q.PropertyDefinitionRecord.replaceDB(db),
		PropertyValueRecord:        q.PropertyValueRecord.replaceDB(db),
		SearchTokenRecord:          q.SearchTokenRecord.replaceDB(db),
		TagRecord:                  q.TagRecord.replaceDB(db),
		TaskRecord:                 q.TaskRecord.replaceDB(db),
		VaultFileRecord:            q.VaultFileRecord.replaceDB(db),
	}
}

type queryCtx struct {
	AssetLinkRecord            IAssetLinkRecordDo
	AssetRecord                IAssetRecordDo
	AttachmentRecord           IAttachmentRecordDo
	DimensionCountRecord       IDimensionCountRecordDo
	FolderRecord               IFolderRecordDo
	IndexMetaRecord            IIndexMetaRecordDo
	LinkRecord                 ILinkRecordDo
	NoteRecord                 INoteRecordDo
	NoteTextRecord             INoteTextRecordDo
	PromptAssetRecord          IPromptAssetRecordDo
	PromptAssetSourceRefRecord IPromptAssetSourceRefRecordDo
	PromptAssetVersionRecord   IPromptAssetVersionRecordDo
	PromptUsageFeedbackRecord  IPromptUsageFeedbackRecordDo
	PropertyDefinitionRecord   IPropertyDefinitionRecordDo
	PropertyValueRecord        IPropertyValueRecordDo
	SearchTokenRecord          ISearchTokenRecordDo
	TagRecord                  ITagRecordDo
	TaskRecord                 ITaskRecordDo
	VaultFileRecord            IVaultFileRecordDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AssetLinkRecord:            q.AssetLinkRecord.WithContext(ctx),
		AssetRecord:                q.AssetRecord.WithContext(ctx),
		AttachmentRecord:           q.AttachmentRecord.WithContext(ctx),
		DimensionCountRecord:       q.DimensionCountRecord.WithContext(ctx),
		FolderRecord:               q.FolderRecord.WithContext(ctx),
		IndexMetaRecord:            q.IndexMetaRecord.WithContext(ctx),
		LinkRecord:                 q.LinkRecord.WithContext(ctx),
		NoteRecord:                 q.NoteRecord.WithContext(ctx),
		NoteTextRecord:             q.NoteTextRecord.WithContext(ctx),
		PromptAssetRecord:          q.PromptAssetRecord.WithContext(ctx),
		PromptAssetSourceRefRecord: q.PromptAssetSourceRefRecord.WithContext(ctx),
		PromptAssetVersionRecord:   q.PromptAssetVersionRecord.WithContext(ctx),
		PromptUsageFeedbackRecord:  q.PromptUsageFeedbackRecord.WithContext(ctx),
		PropertyDefinitionRecord:   q.PropertyDefinitionRecord.WithContext(ctx),
		PropertyValueRecord:        q.PropertyValueRecord.WithContext(ctx),
		SearchTokenRecord:          q.SearchTokenRecord.WithContext(ctx),
		TagRecord:                  q.TagRecord.WithContext(ctx),
		TaskRecord:                 q.TaskRecord.WithContext(ctx),
		VaultFileRecord:            q.VaultFileRecord.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
