// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newIndexMetaRecord(db *gorm.DB, opts ...gen.DOOption) indexMetaRecord {
	_indexMetaRecord := indexMetaRecord{}

	_indexMetaRecord.indexMetaRecordDo.UseDB(db, opts...)
	_indexMetaRecord.indexMetaRecordDo.UseModel(&model.IndexMetaRecord{})

	tableName := _indexMetaRecord.indexMetaRecordDo.TableName()
	_indexMetaRecord.ALL = field.NewAsterisk(tableName)
	_indexMetaRecord.Key = field.NewString(tableName, "key")
	_indexMetaRecord.Value = field.NewString(tableName, "value")
	_indexMetaRecord.UpdatedAt = field.NewString(tableName, "updated_at")

	_indexMetaRecord.fillFieldMap()

	return _indexMetaRecord
}

type indexMetaRecord struct {
	indexMetaRecordDo

	ALL       field.Asterisk
	Key       field.String
	Value     field.String
	UpdatedAt field.String

	fieldMap map[string]field.Expr
}

func (i indexMetaRecord) Table(newTableName string) *indexMetaRecord {
	i.indexMetaRecordDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i indexMetaRecord) As(alias string) *indexMetaRecord {
	i.indexMetaRecordDo.DO = *(i.indexMetaRecordDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *indexMetaRecord) updateTableName(table string) *indexMetaRecord {
	i.ALL = field.NewAsterisk(table)
	i.Key = field.NewString(table, "key")
	i.Value = field.NewString(table, "value")
	i.UpdatedAt = field.NewString(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *indexMetaRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *indexMetaRecord) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 3)
	i.fieldMap["key"] = i.Key
	i.fieldMap["value"] = i.Value
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i indexMetaRecord) clone(db *gorm.DB) indexMetaRecord {
	i.indexMetaRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i indexMetaRecord) replaceDB(db *gorm.DB) indexMetaRecord {
	i.indexMetaRecordDo.ReplaceDB(db)
	return i
}

type indexMetaRecordDo struct{ gen.DO }

type IIndexMetaRecordDo interface {
	gen.SubQuery
	Debug() IIndexMetaRecordDo
	WithContext(ctx context.Context) IIndexMetaRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIndexMetaRecordDo
	WriteDB() IIndexMetaRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIndexMetaRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIndexMetaRecordDo
	Not(conds ...gen.Condition) IIndexMetaRecordDo
	Or(conds ...gen.Condition) IIndexMetaRecordDo
	Select(conds ...field.Expr) IIndexMetaRecordDo
	Where(conds ...gen.Condition) IIndexMetaRecordDo
	Order(conds ...field.Expr) IIndexMetaRecordDo
	Distinct(cols ...field.Expr) IIndexMetaRecordDo
	Omit(cols ...field.Expr) IIndexMetaRecordDo
	Join(table schema.Tabler, on ...field.Expr) IIndexMetaRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIndexMetaRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIndexMetaRecordDo
	Group(cols ...field.Expr) IIndexMetaRecordDo
	Having(conds ...gen.Condition) IIndexMetaRecordDo
	Limit(limit int) IIndexMetaRecordDo
	Offset(offset int) IIndexMetaRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIndexMetaRecordDo
	Unscoped() IIndexMetaRecordDo
	Create(values ...*model.IndexMetaRecord) error
	CreateInBatches(values []*model.IndexMetaRecord, batchSize int) error
	Save(values ...*model.IndexMetaRecord) error
	First() (*model.IndexMetaRecord, error)
	Take() (*model.IndexMetaRecord, error)
	Last() (*model.IndexMetaRecord, error)
	Find() ([]*model.IndexMetaRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IndexMetaRecord, err error)
	FindInBatches(result *[]*model.IndexMetaRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IndexMetaRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIndexMetaRecordDo
	Assign(attrs ...field.AssignExpr) IIndexMetaRecordDo
	Joins(fields ...field.RelationField) IIndexMetaRecordDo
	Preload(fields ...field.RelationField) IIndexMetaRecordDo
	FirstOrInit() (*model.IndexMetaRecord, error)
	FirstOrCreate() (*model.IndexMetaRecord, error)
	FindByPage(offset int, limit int) (result []*model.IndexMetaRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIndexMetaRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i indexMetaRecordDo) Debug() IIndexMetaRecordDo {
	return i.withDO(i.DO.Debug())
}

func (i indexMetaRecordDo) WithContext(ctx context.Context) IIndexMetaRecordDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i indexMetaRecordDo) ReadDB() IIndexMetaRecordDo {
	return i.Clauses(dbresolver.Read)
}

func (i indexMetaRecordDo) WriteDB() IIndexMetaRecordDo {
	return i.Clauses(dbresolver.Write)
}

func (i indexMetaRecordDo) Session(config *gorm.Session) IIndexMetaRecordDo {
	return i.withDO(i.DO.Session(config))
}

func (i indexMetaRecordDo) Clauses(conds ...clause.Expression) IIndexMetaRecordDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i indexMetaRecordDo) Returning(value interface{}, columns ...string) IIndexMetaRecordDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i indexMetaRecordDo) Not(conds ...gen.Condition) IIndexMetaRecordDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i indexMetaRecordDo) Or(conds ...gen.Condition) IIndexMetaRecordDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i indexMetaRecordDo) Select(conds ...field.Expr) IIndexMetaRecordDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i indexMetaRecordDo) Where(conds ...gen.Condition) IIndexMetaRecordDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i indexMetaRecordDo) Order(conds ...field.Expr) IIndexMetaRecordDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i indexMetaRecordDo) Distinct(cols ...field.Expr) IIndexMetaRecordDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i indexMetaRecordDo) Omit(cols ...field.Expr) IIndexMetaRecordDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i indexMetaRecordDo) Join(table schema.Tabler, on ...field.Expr) IIndexMetaRecordDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i indexMetaRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIndexMetaRecordDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i indexMetaRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IIndexMetaRecordDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i indexMetaRecordDo) Group(cols ...field.Expr) IIndexMetaRecordDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i indexMetaRecordDo) Having(conds ...gen.Condition) IIndexMetaRecordDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i indexMetaRecordDo) Limit(limit int) IIndexMetaRecordDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i indexMetaRecordDo) Offset(offset int) IIndexMetaRecordDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i indexMetaRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIndexMetaRecordDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i indexMetaRecordDo) Unscoped() IIndexMetaRecordDo {
	return i.withDO(i.DO.Unscoped())
}

func (i indexMetaRecordDo) Create(values ...*model.IndexMetaRecord) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i indexMetaRecordDo) CreateInBatches(values []*model.IndexMetaRecord, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i indexMetaRecordDo) Save(values ...*model.IndexMetaRecord) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i indexMetaRecordDo) First() (*model.IndexMetaRecord, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IndexMetaRecord), nil
	}
}

func (i indexMetaRecordDo) Take() (*model.IndexMetaRecord, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IndexMetaRecord), nil
	}
}

func (i indexMetaRecordDo) Last() (*model.IndexMetaRecord, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IndexMetaRecord), nil
	}
}

func (i indexMetaRecordDo) Find() ([]*model.IndexMetaRecord, error) {
	result, err := i.DO.Find()
	return result.([]*model.IndexMetaRecord), err
}

func (i indexMetaRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IndexMetaRecord, err error) {
	buf := make([]*model.IndexMetaRecord, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i indexMetaRecordDo) FindInBatches(result *[]*model.IndexMetaRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i indexMetaRecordDo) Attrs(attrs ...field.AssignExpr) IIndexMetaRecordDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i indexMetaRecordDo) Assign(attrs ...field.AssignExpr) IIndexMetaRecordDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i indexMetaRecordDo) Joins(fields ...field.RelationField) IIndexMetaRecordDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i indexMetaRecordDo) Preload(fields ...field.RelationField) IIndexMetaRecordDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i indexMetaRecordDo) FirstOrInit() (*model.IndexMetaRecord, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IndexMetaRecord), nil
	}
}

func (i indexMetaRecordDo) FirstOrCreate() (*model.IndexMetaRecord, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IndexMetaRecord), nil
	}
}

func (i indexMetaRecordDo) FindByPage(offset int, limit int) (result []*model.IndexMetaRecord, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i indexMetaRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i indexMetaRecordDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i indexMetaRecordDo) Delete(models ...*model.IndexMetaRecord) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *indexMetaRecordDo) withDO(do gen.Dao) *indexMetaRecordDo {
	i.DO = *do.(*gen.DO)
	return i
}
