// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newLinkRecord(db *gorm.DB, opts ...gen.DOOption) linkRecord {
	_linkRecord := linkRecord{}

	_linkRecord.linkRecordDo.UseDB(db, opts...)
	_linkRecord.linkRecordDo.UseModel(&model.LinkRecord{})

	tableName := _linkRecord.linkRecordDo.TableName()
	_linkRecord.ALL = field.NewAsterisk(tableName)
	_linkRecord.ID = field.NewUint(tableName, "id")
	_linkRecord.NotePath = field.NewString(tableName, "note_path")
	_linkRecord.Target = field.NewString(tableName, "target")
	_linkRecord.TargetPath = field.NewString(tableName, "target_path")
	_linkRecord.Kind = field.NewString(tableName, "kind")
	_linkRecord.Broken = field.NewBool(tableName, "broken")
	_linkRecord.SourceNoteID = field.NewString(tableName, "source_note_id")
	_linkRecord.TargetNoteID = field.NewString(tableName, "target_note_id")
	_linkRecord.TargetTitle = field.NewString(tableName, "target_title")
	_linkRecord.TargetRaw = field.NewString(tableName, "target_raw")
	_linkRecord.TargetAlias = field.NewString(tableName, "target_alias")
	_linkRecord.TargetHeading = field.NewString(tableName, "target_heading")
	_linkRecord.Status = field.NewString(tableName, "status")
	_linkRecord.Line = field.NewInt(tableName, "line")
	_linkRecord.Evidence = field.NewString(tableName, "evidence")

	_linkRecord.fillFieldMap()

	return _linkRecord
}

type linkRecord struct {
	linkRecordDo

	ALL           field.Asterisk
	ID            field.Uint
	NotePath      field.String
	Target        field.String
	TargetPath    field.String
	Kind          field.String
	Broken        field.Bool
	SourceNoteID  field.String
	TargetNoteID  field.String
	TargetTitle   field.String
	TargetRaw     field.String
	TargetAlias   field.String
	TargetHeading field.String
	Status        field.String
	Line          field.Int
	Evidence      field.String

	fieldMap map[string]field.Expr
}

func (l linkRecord) Table(newTableName string) *linkRecord {
	l.linkRecordDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l linkRecord) As(alias string) *linkRecord {
	l.linkRecordDo.DO = *(l.linkRecordDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *linkRecord) updateTableName(table string) *linkRecord {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewUint(table, "id")
	l.NotePath = field.NewString(table, "note_path")
	l.Target = field.NewString(table, "target")
	l.TargetPath = field.NewString(table, "target_path")
	l.Kind = field.NewString(table, "kind")
	l.Broken = field.NewBool(table, "broken")
	l.SourceNoteID = field.NewString(table, "source_note_id")
	l.TargetNoteID = field.NewString(table, "target_note_id")
	l.TargetTitle = field.NewString(table, "target_title")
	l.TargetRaw = field.NewString(table, "target_raw")
	l.TargetAlias = field.NewString(table, "target_alias")
	l.TargetHeading = field.NewString(table, "target_heading")
	l.Status = field.NewString(table, "status")
	l.Line = field.NewInt(table, "line")
	l.Evidence = field.NewString(table, "evidence")

	l.fillFieldMap()

	return l
}

func (l *linkRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *linkRecord) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 15)
	l.fieldMap["id"] = l.ID
	l.fieldMap["note_path"] = l.NotePath
	l.fieldMap["target"] = l.Target
	l.fieldMap["target_path"] = l.TargetPath
	l.fieldMap["kind"] = l.Kind
	l.fieldMap["broken"] = l.Broken
	l.fieldMap["source_note_id"] = l.SourceNoteID
	l.fieldMap["target_note_id"] = l.TargetNoteID
	l.fieldMap["target_title"] = l.TargetTitle
	l.fieldMap["target_raw"] = l.TargetRaw
	l.fieldMap["target_alias"] = l.TargetAlias
	l.fieldMap["target_heading"] = l.TargetHeading
	l.fieldMap["status"] = l.Status
	l.fieldMap["line"] = l.Line
	l.fieldMap["evidence"] = l.Evidence
}

func (l linkRecord) clone(db *gorm.DB) linkRecord {
	l.linkRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l linkRecord) replaceDB(db *gorm.DB) linkRecord {
	l.linkRecordDo.ReplaceDB(db)
	return l
}

type linkRecordDo struct{ gen.DO }

type ILinkRecordDo interface {
	gen.SubQuery
	Debug() ILinkRecordDo
	WithContext(ctx context.Context) ILinkRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILinkRecordDo
	WriteDB() ILinkRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILinkRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILinkRecordDo
	Not(conds ...gen.Condition) ILinkRecordDo
	Or(conds ...gen.Condition) ILinkRecordDo
	Select(conds ...field.Expr) ILinkRecordDo
	Where(conds ...gen.Condition) ILinkRecordDo
	Order(conds ...field.Expr) ILinkRecordDo
	Distinct(cols ...field.Expr) ILinkRecordDo
	Omit(cols ...field.Expr) ILinkRecordDo
	Join(table schema.Tabler, on ...field.Expr) ILinkRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILinkRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILinkRecordDo
	Group(cols ...field.Expr) ILinkRecordDo
	Having(conds ...gen.Condition) ILinkRecordDo
	Limit(limit int) ILinkRecordDo
	Offset(offset int) ILinkRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILinkRecordDo
	Unscoped() ILinkRecordDo
	Create(values ...*model.LinkRecord) error
	CreateInBatches(values []*model.LinkRecord, batchSize int) error
	Save(values ...*model.LinkRecord) error
	First() (*model.LinkRecord, error)
	Take() (*model.LinkRecord, error)
	Last() (*model.LinkRecord, error)
	Find() ([]*model.LinkRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LinkRecord, err error)
	FindInBatches(result *[]*model.LinkRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LinkRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILinkRecordDo
	Assign(attrs ...field.AssignExpr) ILinkRecordDo
	Joins(fields ...field.RelationField) ILinkRecordDo
	Preload(fields ...field.RelationField) ILinkRecordDo
	FirstOrInit() (*model.LinkRecord, error)
	FirstOrCreate() (*model.LinkRecord, error)
	FindByPage(offset int, limit int) (result []*model.LinkRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILinkRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l linkRecordDo) Debug() ILinkRecordDo {
	return l.withDO(l.DO.Debug())
}

func (l linkRecordDo) WithContext(ctx context.Context) ILinkRecordDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l linkRecordDo) ReadDB() ILinkRecordDo {
	return l.Clauses(dbresolver.Read)
}

func (l linkRecordDo) WriteDB() ILinkRecordDo {
	return l.Clauses(dbresolver.Write)
}

func (l linkRecordDo) Session(config *gorm.Session) ILinkRecordDo {
	return l.withDO(l.DO.Session(config))
}

func (l linkRecordDo) Clauses(conds ...clause.Expression) ILinkRecordDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l linkRecordDo) Returning(value interface{}, columns ...string) ILinkRecordDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l linkRecordDo) Not(conds ...gen.Condition) ILinkRecordDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l linkRecordDo) Or(conds ...gen.Condition) ILinkRecordDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l linkRecordDo) Select(conds ...field.Expr) ILinkRecordDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l linkRecordDo) Where(conds ...gen.Condition) ILinkRecordDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l linkRecordDo) Order(conds ...field.Expr) ILinkRecordDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l linkRecordDo) Distinct(cols ...field.Expr) ILinkRecordDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l linkRecordDo) Omit(cols ...field.Expr) ILinkRecordDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l linkRecordDo) Join(table schema.Tabler, on ...field.Expr) ILinkRecordDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l linkRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILinkRecordDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l linkRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) ILinkRecordDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l linkRecordDo) Group(cols ...field.Expr) ILinkRecordDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l linkRecordDo) Having(conds ...gen.Condition) ILinkRecordDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l linkRecordDo) Limit(limit int) ILinkRecordDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l linkRecordDo) Offset(offset int) ILinkRecordDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l linkRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILinkRecordDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l linkRecordDo) Unscoped() ILinkRecordDo {
	return l.withDO(l.DO.Unscoped())
}

func (l linkRecordDo) Create(values ...*model.LinkRecord) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l linkRecordDo) CreateInBatches(values []*model.LinkRecord, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l linkRecordDo) Save(values ...*model.LinkRecord) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l linkRecordDo) First() (*model.LinkRecord, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkRecord), nil
	}
}

func (l linkRecordDo) Take() (*model.LinkRecord, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkRecord), nil
	}
}

func (l linkRecordDo) Last() (*model.LinkRecord, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkRecord), nil
	}
}

func (l linkRecordDo) Find() ([]*model.LinkRecord, error) {
	result, err := l.DO.Find()
	return result.([]*model.LinkRecord), err
}

func (l linkRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LinkRecord, err error) {
	buf := make([]*model.LinkRecord, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l linkRecordDo) FindInBatches(result *[]*model.LinkRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l linkRecordDo) Attrs(attrs ...field.AssignExpr) ILinkRecordDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l linkRecordDo) Assign(attrs ...field.AssignExpr) ILinkRecordDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l linkRecordDo) Joins(fields ...field.RelationField) ILinkRecordDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l linkRecordDo) Preload(fields ...field.RelationField) ILinkRecordDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l linkRecordDo) FirstOrInit() (*model.LinkRecord, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkRecord), nil
	}
}

func (l linkRecordDo) FirstOrCreate() (*model.LinkRecord, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkRecord), nil
	}
}

func (l linkRecordDo) FindByPage(offset int, limit int) (result []*model.LinkRecord, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l linkRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l linkRecordDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l linkRecordDo) Delete(models ...*model.LinkRecord) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *linkRecordDo) withDO(do gen.Dao) *linkRecordDo {
	l.DO = *do.(*gen.DO)
	return l
}
