// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newNoteTextRecord(db *gorm.DB, opts ...gen.DOOption) noteTextRecord {
	_noteTextRecord := noteTextRecord{}

	_noteTextRecord.noteTextRecordDo.UseDB(db, opts...)
	_noteTextRecord.noteTextRecordDo.UseModel(&model.NoteTextRecord{})

	tableName := _noteTextRecord.noteTextRecordDo.TableName()
	_noteTextRecord.ALL = field.NewAsterisk(tableName)
	_noteTextRecord.NotePath = field.NewString(tableName, "note_path")
	_noteTextRecord.TitleText = field.NewString(tableName, "title_text")
	_noteTextRecord.BodyText = field.NewString(tableName, "body_text")
	_noteTextRecord.Excerpt = field.NewString(tableName, "excerpt")
	_noteTextRecord.WordCount = field.NewInt(tableName, "word_count")

	_noteTextRecord.fillFieldMap()

	return _noteTextRecord
}

type noteTextRecord struct {
	noteTextRecordDo

	ALL       field.Asterisk
	NotePath  field.String
	TitleText field.String
	BodyText  field.String
	Excerpt   field.String
	WordCount field.Int

	fieldMap map[string]field.Expr
}

func (n noteTextRecord) Table(newTableName string) *noteTextRecord {
	n.noteTextRecordDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n noteTextRecord) As(alias string) *noteTextRecord {
	n.noteTextRecordDo.DO = *(n.noteTextRecordDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *noteTextRecord) updateTableName(table string) *noteTextRecord {
	n.ALL = field.NewAsterisk(table)
	n.NotePath = field.NewString(table, "note_path")
	n.TitleText = field.NewString(table, "title_text")
	n.BodyText = field.NewString(table, "body_text")
	n.Excerpt = field.NewString(table, "excerpt")
	n.WordCount = field.NewInt(table, "word_count")

	n.fillFieldMap()

	return n
}

func (n *noteTextRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *noteTextRecord) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 5)
	n.fieldMap["note_path"] = n.NotePath
	n.fieldMap["title_text"] = n.TitleText
	n.fieldMap["body_text"] = n.BodyText
	n.fieldMap["excerpt"] = n.Excerpt
	n.fieldMap["word_count"] = n.WordCount
}

func (n noteTextRecord) clone(db *gorm.DB) noteTextRecord {
	n.noteTextRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n noteTextRecord) replaceDB(db *gorm.DB) noteTextRecord {
	n.noteTextRecordDo.ReplaceDB(db)
	return n
}

type noteTextRecordDo struct{ gen.DO }

type INoteTextRecordDo interface {
	gen.SubQuery
	Debug() INoteTextRecordDo
	WithContext(ctx context.Context) INoteTextRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INoteTextRecordDo
	WriteDB() INoteTextRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INoteTextRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INoteTextRecordDo
	Not(conds ...gen.Condition) INoteTextRecordDo
	Or(conds ...gen.Condition) INoteTextRecordDo
	Select(conds ...field.Expr) INoteTextRecordDo
	Where(conds ...gen.Condition) INoteTextRecordDo
	Order(conds ...field.Expr) INoteTextRecordDo
	Distinct(cols ...field.Expr) INoteTextRecordDo
	Omit(cols ...field.Expr) INoteTextRecordDo
	Join(table schema.Tabler, on ...field.Expr) INoteTextRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INoteTextRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) INoteTextRecordDo
	Group(cols ...field.Expr) INoteTextRecordDo
	Having(conds ...gen.Condition) INoteTextRecordDo
	Limit(limit int) INoteTextRecordDo
	Offset(offset int) INoteTextRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INoteTextRecordDo
	Unscoped() INoteTextRecordDo
	Create(values ...*model.NoteTextRecord) error
	CreateInBatches(values []*model.NoteTextRecord, batchSize int) error
	Save(values ...*model.NoteTextRecord) error
	First() (*model.NoteTextRecord, error)
	Take() (*model.NoteTextRecord, error)
	Last() (*model.NoteTextRecord, error)
	Find() ([]*model.NoteTextRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NoteTextRecord, err error)
	FindInBatches(result *[]*model.NoteTextRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NoteTextRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INoteTextRecordDo
	Assign(attrs ...field.AssignExpr) INoteTextRecordDo
	Joins(fields ...field.RelationField) INoteTextRecordDo
	Preload(fields ...field.RelationField) INoteTextRecordDo
	FirstOrInit() (*model.NoteTextRecord, error)
	FirstOrCreate() (*model.NoteTextRecord, error)
	FindByPage(offset int, limit int) (result []*model.NoteTextRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INoteTextRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n noteTextRecordDo) Debug() INoteTextRecordDo {
	return n.withDO(n.DO.Debug())
}

func (n noteTextRecordDo) WithContext(ctx context.Context) INoteTextRecordDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n noteTextRecordDo) ReadDB() INoteTextRecordDo {
	return n.Clauses(dbresolver.Read)
}

func (n noteTextRecordDo) WriteDB() INoteTextRecordDo {
	return n.Clauses(dbresolver.Write)
}

func (n noteTextRecordDo) Session(config *gorm.Session) INoteTextRecordDo {
	return n.withDO(n.DO.Session(config))
}

func (n noteTextRecordDo) Clauses(conds ...clause.Expression) INoteTextRecordDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n noteTextRecordDo) Returning(value interface{}, columns ...string) INoteTextRecordDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n noteTextRecordDo) Not(conds ...gen.Condition) INoteTextRecordDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n noteTextRecordDo) Or(conds ...gen.Condition) INoteTextRecordDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n noteTextRecordDo) Select(conds ...field.Expr) INoteTextRecordDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n noteTextRecordDo) Where(conds ...gen.Condition) INoteTextRecordDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n noteTextRecordDo) Order(conds ...field.Expr) INoteTextRecordDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n noteTextRecordDo) Distinct(cols ...field.Expr) INoteTextRecordDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n noteTextRecordDo) Omit(cols ...field.Expr) INoteTextRecordDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n noteTextRecordDo) Join(table schema.Tabler, on ...field.Expr) INoteTextRecordDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n noteTextRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) INoteTextRecordDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n noteTextRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) INoteTextRecordDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n noteTextRecordDo) Group(cols ...field.Expr) INoteTextRecordDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n noteTextRecordDo) Having(conds ...gen.Condition) INoteTextRecordDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n noteTextRecordDo) Limit(limit int) INoteTextRecordDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n noteTextRecordDo) Offset(offset int) INoteTextRecordDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n noteTextRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INoteTextRecordDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n noteTextRecordDo) Unscoped() INoteTextRecordDo {
	return n.withDO(n.DO.Unscoped())
}

func (n noteTextRecordDo) Create(values ...*model.NoteTextRecord) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n noteTextRecordDo) CreateInBatches(values []*model.NoteTextRecord, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n noteTextRecordDo) Save(values ...*model.NoteTextRecord) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n noteTextRecordDo) First() (*model.NoteTextRecord, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteTextRecord), nil
	}
}

func (n noteTextRecordDo) Take() (*model.NoteTextRecord, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteTextRecord), nil
	}
}

func (n noteTextRecordDo) Last() (*model.NoteTextRecord, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteTextRecord), nil
	}
}

func (n noteTextRecordDo) Find() ([]*model.NoteTextRecord, error) {
	result, err := n.DO.Find()
	return result.([]*model.NoteTextRecord), err
}

func (n noteTextRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NoteTextRecord, err error) {
	buf := make([]*model.NoteTextRecord, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n noteTextRecordDo) FindInBatches(result *[]*model.NoteTextRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n noteTextRecordDo) Attrs(attrs ...field.AssignExpr) INoteTextRecordDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n noteTextRecordDo) Assign(attrs ...field.AssignExpr) INoteTextRecordDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n noteTextRecordDo) Joins(fields ...field.RelationField) INoteTextRecordDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n noteTextRecordDo) Preload(fields ...field.RelationField) INoteTextRecordDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n noteTextRecordDo) FirstOrInit() (*model.NoteTextRecord, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteTextRecord), nil
	}
}

func (n noteTextRecordDo) FirstOrCreate() (*model.NoteTextRecord, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteTextRecord), nil
	}
}

func (n noteTextRecordDo) FindByPage(offset int, limit int) (result []*model.NoteTextRecord, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n noteTextRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n noteTextRecordDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n noteTextRecordDo) Delete(models ...*model.NoteTextRecord) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *noteTextRecordDo) withDO(do gen.Dao) *noteTextRecordDo {
	n.DO = *do.(*gen.DO)
	return n
}
