// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newNoteRecord(db *gorm.DB, opts ...gen.DOOption) noteRecord {
	_noteRecord := noteRecord{}

	_noteRecord.noteRecordDo.UseDB(db, opts...)
	_noteRecord.noteRecordDo.UseModel(&model.NoteRecord{})

	tableName := _noteRecord.noteRecordDo.TableName()
	_noteRecord.ALL = field.NewAsterisk(tableName)
	_noteRecord.Path = field.NewString(tableName, "path")
	_noteRecord.NoteID = field.NewString(tableName, "note_id")
	_noteRecord.Title = field.NewString(tableName, "title")
	_noteRecord.Filename = field.NewString(tableName, "filename")
	_noteRecord.Stem = field.NewString(tableName, "stem")
	_noteRecord.ObjectKind = field.NewString(tableName, "object_kind")
	_noteRecord.ManagedStatus = field.NewString(tableName, "managed_status")
	_noteRecord.Project = field.NewString(tableName, "project")
	_noteRecord.Group_ = field.NewString(tableName, "group")
	_noteRecord.Folder = field.NewString(tableName, "folder")
	_noteRecord.Kind = field.NewString(tableName, "kind")
	_noteRecord.Status = field.NewString(tableName, "status")
	_noteRecord.LifecycleStatus = field.NewString(tableName, "lifecycle_status")
	_noteRecord.CreatedAt = field.NewString(tableName, "created_at")
	_noteRecord.UpdatedAt = field.NewString(tableName, "updated_at")
	_noteRecord.SourceHash = field.NewString(tableName, "source_hash")
	_noteRecord.ModifiedUnix = field.NewInt64(tableName, "modified_unix")
	_noteRecord.Size = field.NewInt64(tableName, "size")
	_noteRecord.IsSystem = field.NewBool(tableName, "is_system")

	_noteRecord.fillFieldMap()

	return _noteRecord
}

type noteRecord struct {
	noteRecordDo

	ALL             field.Asterisk
	Path            field.String
	NoteID          field.String
	Title           field.String
	Filename        field.String
	Stem            field.String
	ObjectKind      field.String
	ManagedStatus   field.String
	Project         field.String
	Group_          field.String
	Folder          field.String
	Kind            field.String
	Status          field.String
	LifecycleStatus field.String
	CreatedAt       field.String
	UpdatedAt       field.String
	SourceHash      field.String
	ModifiedUnix    field.Int64
	Size            field.Int64
	IsSystem        field.Bool

	fieldMap map[string]field.Expr
}

func (n noteRecord) Table(newTableName string) *noteRecord {
	n.noteRecordDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n noteRecord) As(alias string) *noteRecord {
	n.noteRecordDo.DO = *(n.noteRecordDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *noteRecord) updateTableName(table string) *noteRecord {
	n.ALL = field.NewAsterisk(table)
	n.Path = field.NewString(table, "path")
	n.NoteID = field.NewString(table, "note_id")
	n.Title = field.NewString(table, "title")
	n.Filename = field.NewString(table, "filename")
	n.Stem = field.NewString(table, "stem")
	n.ObjectKind = field.NewString(table, "object_kind")
	n.ManagedStatus = field.NewString(table, "managed_status")
	n.Project = field.NewString(table, "project")
	n.Group_ = field.NewString(table, "group")
	n.Folder = field.NewString(table, "folder")
	n.Kind = field.NewString(table, "kind")
	n.Status = field.NewString(table, "status")
	n.LifecycleStatus = field.NewString(table, "lifecycle_status")
	n.CreatedAt = field.NewString(table, "created_at")
	n.UpdatedAt = field.NewString(table, "updated_at")
	n.SourceHash = field.NewString(table, "source_hash")
	n.ModifiedUnix = field.NewInt64(table, "modified_unix")
	n.Size = field.NewInt64(table, "size")
	n.IsSystem = field.NewBool(table, "is_system")

	n.fillFieldMap()

	return n
}

func (n *noteRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *noteRecord) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 19)
	n.fieldMap["path"] = n.Path
	n.fieldMap["note_id"] = n.NoteID
	n.fieldMap["title"] = n.Title
	n.fieldMap["filename"] = n.Filename
	n.fieldMap["stem"] = n.Stem
	n.fieldMap["object_kind"] = n.ObjectKind
	n.fieldMap["managed_status"] = n.ManagedStatus
	n.fieldMap["project"] = n.Project
	n.fieldMap["group"] = n.Group_
	n.fieldMap["folder"] = n.Folder
	n.fieldMap["kind"] = n.Kind
	n.fieldMap["status"] = n.Status
	n.fieldMap["lifecycle_status"] = n.LifecycleStatus
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
	n.fieldMap["source_hash"] = n.SourceHash
	n.fieldMap["modified_unix"] = n.ModifiedUnix
	n.fieldMap["size"] = n.Size
	n.fieldMap["is_system"] = n.IsSystem
}

func (n noteRecord) clone(db *gorm.DB) noteRecord {
	n.noteRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n noteRecord) replaceDB(db *gorm.DB) noteRecord {
	n.noteRecordDo.ReplaceDB(db)
	return n
}

type noteRecordDo struct{ gen.DO }

type INoteRecordDo interface {
	gen.SubQuery
	Debug() INoteRecordDo
	WithContext(ctx context.Context) INoteRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INoteRecordDo
	WriteDB() INoteRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INoteRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INoteRecordDo
	Not(conds ...gen.Condition) INoteRecordDo
	Or(conds ...gen.Condition) INoteRecordDo
	Select(conds ...field.Expr) INoteRecordDo
	Where(conds ...gen.Condition) INoteRecordDo
	Order(conds ...field.Expr) INoteRecordDo
	Distinct(cols ...field.Expr) INoteRecordDo
	Omit(cols ...field.Expr) INoteRecordDo
	Join(table schema.Tabler, on ...field.Expr) INoteRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INoteRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) INoteRecordDo
	Group(cols ...field.Expr) INoteRecordDo
	Having(conds ...gen.Condition) INoteRecordDo
	Limit(limit int) INoteRecordDo
	Offset(offset int) INoteRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INoteRecordDo
	Unscoped() INoteRecordDo
	Create(values ...*model.NoteRecord) error
	CreateInBatches(values []*model.NoteRecord, batchSize int) error
	Save(values ...*model.NoteRecord) error
	First() (*model.NoteRecord, error)
	Take() (*model.NoteRecord, error)
	Last() (*model.NoteRecord, error)
	Find() ([]*model.NoteRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NoteRecord, err error)
	FindInBatches(result *[]*model.NoteRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NoteRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INoteRecordDo
	Assign(attrs ...field.AssignExpr) INoteRecordDo
	Joins(fields ...field.RelationField) INoteRecordDo
	Preload(fields ...field.RelationField) INoteRecordDo
	FirstOrInit() (*model.NoteRecord, error)
	FirstOrCreate() (*model.NoteRecord, error)
	FindByPage(offset int, limit int) (result []*model.NoteRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INoteRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n noteRecordDo) Debug() INoteRecordDo {
	return n.withDO(n.DO.Debug())
}

func (n noteRecordDo) WithContext(ctx context.Context) INoteRecordDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n noteRecordDo) ReadDB() INoteRecordDo {
	return n.Clauses(dbresolver.Read)
}

func (n noteRecordDo) WriteDB() INoteRecordDo {
	return n.Clauses(dbresolver.Write)
}

func (n noteRecordDo) Session(config *gorm.Session) INoteRecordDo {
	return n.withDO(n.DO.Session(config))
}

func (n noteRecordDo) Clauses(conds ...clause.Expression) INoteRecordDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n noteRecordDo) Returning(value interface{}, columns ...string) INoteRecordDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n noteRecordDo) Not(conds ...gen.Condition) INoteRecordDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n noteRecordDo) Or(conds ...gen.Condition) INoteRecordDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n noteRecordDo) Select(conds ...field.Expr) INoteRecordDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n noteRecordDo) Where(conds ...gen.Condition) INoteRecordDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n noteRecordDo) Order(conds ...field.Expr) INoteRecordDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n noteRecordDo) Distinct(cols ...field.Expr) INoteRecordDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n noteRecordDo) Omit(cols ...field.Expr) INoteRecordDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n noteRecordDo) Join(table schema.Tabler, on ...field.Expr) INoteRecordDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n noteRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) INoteRecordDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n noteRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) INoteRecordDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n noteRecordDo) Group(cols ...field.Expr) INoteRecordDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n noteRecordDo) Having(conds ...gen.Condition) INoteRecordDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n noteRecordDo) Limit(limit int) INoteRecordDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n noteRecordDo) Offset(offset int) INoteRecordDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n noteRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INoteRecordDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n noteRecordDo) Unscoped() INoteRecordDo {
	return n.withDO(n.DO.Unscoped())
}

func (n noteRecordDo) Create(values ...*model.NoteRecord) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n noteRecordDo) CreateInBatches(values []*model.NoteRecord, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n noteRecordDo) Save(values ...*model.NoteRecord) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n noteRecordDo) First() (*model.NoteRecord, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteRecord), nil
	}
}

func (n noteRecordDo) Take() (*model.NoteRecord, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteRecord), nil
	}
}

func (n noteRecordDo) Last() (*model.NoteRecord, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteRecord), nil
	}
}

func (n noteRecordDo) Find() ([]*model.NoteRecord, error) {
	result, err := n.DO.Find()
	return result.([]*model.NoteRecord), err
}

func (n noteRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NoteRecord, err error) {
	buf := make([]*model.NoteRecord, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n noteRecordDo) FindInBatches(result *[]*model.NoteRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n noteRecordDo) Attrs(attrs ...field.AssignExpr) INoteRecordDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n noteRecordDo) Assign(attrs ...field.AssignExpr) INoteRecordDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n noteRecordDo) Joins(fields ...field.RelationField) INoteRecordDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n noteRecordDo) Preload(fields ...field.RelationField) INoteRecordDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n noteRecordDo) FirstOrInit() (*model.NoteRecord, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteRecord), nil
	}
}

func (n noteRecordDo) FirstOrCreate() (*model.NoteRecord, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteRecord), nil
	}
}

func (n noteRecordDo) FindByPage(offset int, limit int) (result []*model.NoteRecord, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n noteRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n noteRecordDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n noteRecordDo) Delete(models ...*model.NoteRecord) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *noteRecordDo) withDO(do gen.Dao) *noteRecordDo {
	n.DO = *do.(*gen.DO)
	return n
}
