// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newPromptAssetVersionRecord(db *gorm.DB, opts ...gen.DOOption) promptAssetVersionRecord {
	_promptAssetVersionRecord := promptAssetVersionRecord{}

	_promptAssetVersionRecord.promptAssetVersionRecordDo.UseDB(db, opts...)
	_promptAssetVersionRecord.promptAssetVersionRecordDo.UseModel(&model.PromptAssetVersionRecord{})

	tableName := _promptAssetVersionRecord.promptAssetVersionRecordDo.TableName()
	_promptAssetVersionRecord.ALL = field.NewAsterisk(tableName)
	_promptAssetVersionRecord.VersionID = field.NewString(tableName, "version_id")
	_promptAssetVersionRecord.PromptAssetID = field.NewString(tableName, "prompt_asset_id")
	_promptAssetVersionRecord.PromptTemplate = field.NewString(tableName, "prompt_template")
	_promptAssetVersionRecord.PromptTemplateHash = field.NewString(tableName, "prompt_template_hash")
	_promptAssetVersionRecord.VariablesJSON = field.NewString(tableName, "variables_json")
	_promptAssetVersionRecord.ConstraintsJSON = field.NewString(tableName, "constraints_json")
	_promptAssetVersionRecord.ReviewGuidance = field.NewString(tableName, "review_guidance")
	_promptAssetVersionRecord.CreatedAt = field.NewString(tableName, "created_at")

	_promptAssetVersionRecord.fillFieldMap()

	return _promptAssetVersionRecord
}

type promptAssetVersionRecord struct {
	promptAssetVersionRecordDo

	ALL                field.Asterisk
	VersionID          field.String
	PromptAssetID      field.String
	PromptTemplate     field.String
	PromptTemplateHash field.String
	VariablesJSON      field.String
	ConstraintsJSON    field.String
	ReviewGuidance     field.String
	CreatedAt          field.String

	fieldMap map[string]field.Expr
}

func (p promptAssetVersionRecord) Table(newTableName string) *promptAssetVersionRecord {
	p.promptAssetVersionRecordDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promptAssetVersionRecord) As(alias string) *promptAssetVersionRecord {
	p.promptAssetVersionRecordDo.DO = *(p.promptAssetVersionRecordDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promptAssetVersionRecord) updateTableName(table string) *promptAssetVersionRecord {
	p.ALL = field.NewAsterisk(table)
	p.VersionID = field.NewString(table, "version_id")
	p.PromptAssetID = field.NewString(table, "prompt_asset_id")
	p.PromptTemplate = field.NewString(table, "prompt_template")
	p.PromptTemplateHash = field.NewString(table, "prompt_template_hash")
	p.VariablesJSON = field.NewString(table, "variables_json")
	p.ConstraintsJSON = field.NewString(table, "constraints_json")
	p.ReviewGuidance = field.NewString(table, "review_guidance")
	p.CreatedAt = field.NewString(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *promptAssetVersionRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promptAssetVersionRecord) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 8)
	p.fieldMap["version_id"] = p.VersionID
	p.fieldMap["prompt_asset_id"] = p.PromptAssetID
	p.fieldMap["prompt_template"] = p.PromptTemplate
	p.fieldMap["prompt_template_hash"] = p.PromptTemplateHash
	p.fieldMap["variables_json"] = p.VariablesJSON
	p.fieldMap["constraints_json"] = p.ConstraintsJSON
	p.fieldMap["review_guidance"] = p.ReviewGuidance
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p promptAssetVersionRecord) clone(db *gorm.DB) promptAssetVersionRecord {
	p.promptAssetVersionRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promptAssetVersionRecord) replaceDB(db *gorm.DB) promptAssetVersionRecord {
	p.promptAssetVersionRecordDo.ReplaceDB(db)
	return p
}

type promptAssetVersionRecordDo struct{ gen.DO }

type IPromptAssetVersionRecordDo interface {
	gen.SubQuery
	Debug() IPromptAssetVersionRecordDo
	WithContext(ctx context.Context) IPromptAssetVersionRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromptAssetVersionRecordDo
	WriteDB() IPromptAssetVersionRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromptAssetVersionRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromptAssetVersionRecordDo
	Not(conds ...gen.Condition) IPromptAssetVersionRecordDo
	Or(conds ...gen.Condition) IPromptAssetVersionRecordDo
	Select(conds ...field.Expr) IPromptAssetVersionRecordDo
	Where(conds ...gen.Condition) IPromptAssetVersionRecordDo
	Order(conds ...field.Expr) IPromptAssetVersionRecordDo
	Distinct(cols ...field.Expr) IPromptAssetVersionRecordDo
	Omit(cols ...field.Expr) IPromptAssetVersionRecordDo
	Join(table schema.Tabler, on ...field.Expr) IPromptAssetVersionRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromptAssetVersionRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromptAssetVersionRecordDo
	Group(cols ...field.Expr) IPromptAssetVersionRecordDo
	Having(conds ...gen.Condition) IPromptAssetVersionRecordDo
	Limit(limit int) IPromptAssetVersionRecordDo
	Offset(offset int) IPromptAssetVersionRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromptAssetVersionRecordDo
	Unscoped() IPromptAssetVersionRecordDo
	Create(values ...*model.PromptAssetVersionRecord) error
	CreateInBatches(values []*model.PromptAssetVersionRecord, batchSize int) error
	Save(values ...*model.PromptAssetVersionRecord) error
	First() (*model.PromptAssetVersionRecord, error)
	Take() (*model.PromptAssetVersionRecord, error)
	Last() (*model.PromptAssetVersionRecord, error)
	Find() ([]*model.PromptAssetVersionRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PromptAssetVersionRecord, err error)
	FindInBatches(result *[]*model.PromptAssetVersionRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PromptAssetVersionRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromptAssetVersionRecordDo
	Assign(attrs ...field.AssignExpr) IPromptAssetVersionRecordDo
	Joins(fields ...field.RelationField) IPromptAssetVersionRecordDo
	Preload(fields ...field.RelationField) IPromptAssetVersionRecordDo
	FirstOrInit() (*model.PromptAssetVersionRecord, error)
	FirstOrCreate() (*model.PromptAssetVersionRecord, error)
	FindByPage(offset int, limit int) (result []*model.PromptAssetVersionRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromptAssetVersionRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promptAssetVersionRecordDo) Debug() IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Debug())
}

func (p promptAssetVersionRecordDo) WithContext(ctx context.Context) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promptAssetVersionRecordDo) ReadDB() IPromptAssetVersionRecordDo {
	return p.Clauses(dbresolver.Read)
}

func (p promptAssetVersionRecordDo) WriteDB() IPromptAssetVersionRecordDo {
	return p.Clauses(dbresolver.Write)
}

func (p promptAssetVersionRecordDo) Session(config *gorm.Session) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Session(config))
}

func (p promptAssetVersionRecordDo) Clauses(conds ...clause.Expression) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promptAssetVersionRecordDo) Returning(value interface{}, columns ...string) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promptAssetVersionRecordDo) Not(conds ...gen.Condition) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promptAssetVersionRecordDo) Or(conds ...gen.Condition) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promptAssetVersionRecordDo) Select(conds ...field.Expr) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promptAssetVersionRecordDo) Where(conds ...gen.Condition) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promptAssetVersionRecordDo) Order(conds ...field.Expr) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promptAssetVersionRecordDo) Distinct(cols ...field.Expr) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promptAssetVersionRecordDo) Omit(cols ...field.Expr) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promptAssetVersionRecordDo) Join(table schema.Tabler, on ...field.Expr) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promptAssetVersionRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promptAssetVersionRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promptAssetVersionRecordDo) Group(cols ...field.Expr) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promptAssetVersionRecordDo) Having(conds ...gen.Condition) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promptAssetVersionRecordDo) Limit(limit int) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promptAssetVersionRecordDo) Offset(offset int) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promptAssetVersionRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promptAssetVersionRecordDo) Unscoped() IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promptAssetVersionRecordDo) Create(values ...*model.PromptAssetVersionRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promptAssetVersionRecordDo) CreateInBatches(values []*model.PromptAssetVersionRecord, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promptAssetVersionRecordDo) Save(values ...*model.PromptAssetVersionRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promptAssetVersionRecordDo) First() (*model.PromptAssetVersionRecord, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetVersionRecord), nil
	}
}

func (p promptAssetVersionRecordDo) Take() (*model.PromptAssetVersionRecord, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetVersionRecord), nil
	}
}

func (p promptAssetVersionRecordDo) Last() (*model.PromptAssetVersionRecord, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetVersionRecord), nil
	}
}

func (p promptAssetVersionRecordDo) Find() ([]*model.PromptAssetVersionRecord, error) {
	result, err := p.DO.Find()
	return result.([]*model.PromptAssetVersionRecord), err
}

func (p promptAssetVersionRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PromptAssetVersionRecord, err error) {
	buf := make([]*model.PromptAssetVersionRecord, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promptAssetVersionRecordDo) FindInBatches(result *[]*model.PromptAssetVersionRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promptAssetVersionRecordDo) Attrs(attrs ...field.AssignExpr) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promptAssetVersionRecordDo) Assign(attrs ...field.AssignExpr) IPromptAssetVersionRecordDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promptAssetVersionRecordDo) Joins(fields ...field.RelationField) IPromptAssetVersionRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promptAssetVersionRecordDo) Preload(fields ...field.RelationField) IPromptAssetVersionRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promptAssetVersionRecordDo) FirstOrInit() (*model.PromptAssetVersionRecord, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetVersionRecord), nil
	}
}

func (p promptAssetVersionRecordDo) FirstOrCreate() (*model.PromptAssetVersionRecord, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetVersionRecord), nil
	}
}

func (p promptAssetVersionRecordDo) FindByPage(offset int, limit int) (result []*model.PromptAssetVersionRecord, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promptAssetVersionRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promptAssetVersionRecordDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promptAssetVersionRecordDo) Delete(models ...*model.PromptAssetVersionRecord) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promptAssetVersionRecordDo) withDO(do gen.Dao) *promptAssetVersionRecordDo {
	p.DO = *do.(*gen.DO)
	return p
}
