// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newPromptUsageFeedbackRecord(db *gorm.DB, opts ...gen.DOOption) promptUsageFeedbackRecord {
	_promptUsageFeedbackRecord := promptUsageFeedbackRecord{}

	_promptUsageFeedbackRecord.promptUsageFeedbackRecordDo.UseDB(db, opts...)
	_promptUsageFeedbackRecord.promptUsageFeedbackRecordDo.UseModel(&model.PromptUsageFeedbackRecord{})

	tableName := _promptUsageFeedbackRecord.promptUsageFeedbackRecordDo.TableName()
	_promptUsageFeedbackRecord.ALL = field.NewAsterisk(tableName)
	_promptUsageFeedbackRecord.FeedbackID = field.NewString(tableName, "feedback_id")
	_promptUsageFeedbackRecord.PromptAssetID = field.NewString(tableName, "prompt_asset_id")
	_promptUsageFeedbackRecord.VersionID = field.NewString(tableName, "version_id")
	_promptUsageFeedbackRecord.PromptTemplateHash = field.NewString(tableName, "prompt_template_hash")
	_promptUsageFeedbackRecord.ExternalRunRef = field.NewString(tableName, "external_run_ref")
	_promptUsageFeedbackRecord.Decision = field.NewString(tableName, "decision")
	_promptUsageFeedbackRecord.Reason = field.NewString(tableName, "reason")
	_promptUsageFeedbackRecord.ArtifactRefsJSON = field.NewString(tableName, "artifact_refs_json")
	_promptUsageFeedbackRecord.ImportedAt = field.NewString(tableName, "imported_at")

	_promptUsageFeedbackRecord.fillFieldMap()

	return _promptUsageFeedbackRecord
}

type promptUsageFeedbackRecord struct {
	promptUsageFeedbackRecordDo

	ALL                field.Asterisk
	FeedbackID         field.String
	PromptAssetID      field.String
	VersionID          field.String
	PromptTemplateHash field.String
	ExternalRunRef     field.String
	Decision           field.String
	Reason             field.String
	ArtifactRefsJSON   field.String
	ImportedAt         field.String

	fieldMap map[string]field.Expr
}

func (p promptUsageFeedbackRecord) Table(newTableName string) *promptUsageFeedbackRecord {
	p.promptUsageFeedbackRecordDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promptUsageFeedbackRecord) As(alias string) *promptUsageFeedbackRecord {
	p.promptUsageFeedbackRecordDo.DO = *(p.promptUsageFeedbackRecordDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promptUsageFeedbackRecord) updateTableName(table string) *promptUsageFeedbackRecord {
	p.ALL = field.NewAsterisk(table)
	p.FeedbackID = field.NewString(table, "feedback_id")
	p.PromptAssetID = field.NewString(table, "prompt_asset_id")
	p.VersionID = field.NewString(table, "version_id")
	p.PromptTemplateHash = field.NewString(table, "prompt_template_hash")
	p.ExternalRunRef = field.NewString(table, "external_run_ref")
	p.Decision = field.NewString(table, "decision")
	p.Reason = field.NewString(table, "reason")
	p.ArtifactRefsJSON = field.NewString(table, "artifact_refs_json")
	p.ImportedAt = field.NewString(table, "imported_at")

	p.fillFieldMap()

	return p
}

func (p *promptUsageFeedbackRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promptUsageFeedbackRecord) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["feedback_id"] = p.FeedbackID
	p.fieldMap["prompt_asset_id"] = p.PromptAssetID
	p.fieldMap["version_id"] = p.VersionID
	p.fieldMap["prompt_template_hash"] = p.PromptTemplateHash
	p.fieldMap["external_run_ref"] = p.ExternalRunRef
	p.fieldMap["decision"] = p.Decision
	p.fieldMap["reason"] = p.Reason
	p.fieldMap["artifact_refs_json"] = p.ArtifactRefsJSON
	p.fieldMap["imported_at"] = p.ImportedAt
}

func (p promptUsageFeedbackRecord) clone(db *gorm.DB) promptUsageFeedbackRecord {
	p.promptUsageFeedbackRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promptUsageFeedbackRecord) replaceDB(db *gorm.DB) promptUsageFeedbackRecord {
	p.promptUsageFeedbackRecordDo.ReplaceDB(db)
	return p
}

type promptUsageFeedbackRecordDo struct{ gen.DO }

type IPromptUsageFeedbackRecordDo interface {
	gen.SubQuery
	Debug() IPromptUsageFeedbackRecordDo
	WithContext(ctx context.Context) IPromptUsageFeedbackRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromptUsageFeedbackRecordDo
	WriteDB() IPromptUsageFeedbackRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromptUsageFeedbackRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromptUsageFeedbackRecordDo
	Not(conds ...gen.Condition) IPromptUsageFeedbackRecordDo
	Or(conds ...gen.Condition) IPromptUsageFeedbackRecordDo
	Select(conds ...field.Expr) IPromptUsageFeedbackRecordDo
	Where(conds ...gen.Condition) IPromptUsageFeedbackRecordDo
	Order(conds ...field.Expr) IPromptUsageFeedbackRecordDo
	Distinct(cols ...field.Expr) IPromptUsageFeedbackRecordDo
	Omit(cols ...field.Expr) IPromptUsageFeedbackRecordDo
	Join(table schema.Tabler, on ...field.Expr) IPromptUsageFeedbackRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromptUsageFeedbackRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromptUsageFeedbackRecordDo
	Group(cols ...field.Expr) IPromptUsageFeedbackRecordDo
	Having(conds ...gen.Condition) IPromptUsageFeedbackRecordDo
	Limit(limit int) IPromptUsageFeedbackRecordDo
	Offset(offset int) IPromptUsageFeedbackRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromptUsageFeedbackRecordDo
	Unscoped() IPromptUsageFeedbackRecordDo
	Create(values ...*model.PromptUsageFeedbackRecord) error
	CreateInBatches(values []*model.PromptUsageFeedbackRecord, batchSize int) error
	Save(values ...*model.PromptUsageFeedbackRecord) error
	First() (*model.PromptUsageFeedbackRecord, error)
	Take() (*model.PromptUsageFeedbackRecord, error)
	Last() (*model.PromptUsageFeedbackRecord, error)
	Find() ([]*model.PromptUsageFeedbackRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PromptUsageFeedbackRecord, err error)
	FindInBatches(result *[]*model.PromptUsageFeedbackRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PromptUsageFeedbackRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromptUsageFeedbackRecordDo
	Assign(attrs ...field.AssignExpr) IPromptUsageFeedbackRecordDo
	Joins(fields ...field.RelationField) IPromptUsageFeedbackRecordDo
	Preload(fields ...field.RelationField) IPromptUsageFeedbackRecordDo
	FirstOrInit() (*model.PromptUsageFeedbackRecord, error)
	FirstOrCreate() (*model.PromptUsageFeedbackRecord, error)
	FindByPage(offset int, limit int) (result []*model.PromptUsageFeedbackRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromptUsageFeedbackRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promptUsageFeedbackRecordDo) Debug() IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Debug())
}

func (p promptUsageFeedbackRecordDo) WithContext(ctx context.Context) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promptUsageFeedbackRecordDo) ReadDB() IPromptUsageFeedbackRecordDo {
	return p.Clauses(dbresolver.Read)
}

func (p promptUsageFeedbackRecordDo) WriteDB() IPromptUsageFeedbackRecordDo {
	return p.Clauses(dbresolver.Write)
}

func (p promptUsageFeedbackRecordDo) Session(config *gorm.Session) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Session(config))
}

func (p promptUsageFeedbackRecordDo) Clauses(conds ...clause.Expression) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promptUsageFeedbackRecordDo) Returning(value interface{}, columns ...string) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promptUsageFeedbackRecordDo) Not(conds ...gen.Condition) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promptUsageFeedbackRecordDo) Or(conds ...gen.Condition) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promptUsageFeedbackRecordDo) Select(conds ...field.Expr) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promptUsageFeedbackRecordDo) Where(conds ...gen.Condition) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promptUsageFeedbackRecordDo) Order(conds ...field.Expr) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promptUsageFeedbackRecordDo) Distinct(cols ...field.Expr) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promptUsageFeedbackRecordDo) Omit(cols ...field.Expr) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promptUsageFeedbackRecordDo) Join(table schema.Tabler, on ...field.Expr) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promptUsageFeedbackRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promptUsageFeedbackRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promptUsageFeedbackRecordDo) Group(cols ...field.Expr) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promptUsageFeedbackRecordDo) Having(conds ...gen.Condition) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promptUsageFeedbackRecordDo) Limit(limit int) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promptUsageFeedbackRecordDo) Offset(offset int) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promptUsageFeedbackRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promptUsageFeedbackRecordDo) Unscoped() IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promptUsageFeedbackRecordDo) Create(values ...*model.PromptUsageFeedbackRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promptUsageFeedbackRecordDo) CreateInBatches(values []*model.PromptUsageFeedbackRecord, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promptUsageFeedbackRecordDo) Save(values ...*model.PromptUsageFeedbackRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promptUsageFeedbackRecordDo) First() (*model.PromptUsageFeedbackRecord, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptUsageFeedbackRecord), nil
	}
}

func (p promptUsageFeedbackRecordDo) Take() (*model.PromptUsageFeedbackRecord, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptUsageFeedbackRecord), nil
	}
}

func (p promptUsageFeedbackRecordDo) Last() (*model.PromptUsageFeedbackRecord, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptUsageFeedbackRecord), nil
	}
}

func (p promptUsageFeedbackRecordDo) Find() ([]*model.PromptUsageFeedbackRecord, error) {
	result, err := p.DO.Find()
	return result.([]*model.PromptUsageFeedbackRecord), err
}

func (p promptUsageFeedbackRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PromptUsageFeedbackRecord, err error) {
	buf := make([]*model.PromptUsageFeedbackRecord, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promptUsageFeedbackRecordDo) FindInBatches(result *[]*model.PromptUsageFeedbackRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promptUsageFeedbackRecordDo) Attrs(attrs ...field.AssignExpr) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promptUsageFeedbackRecordDo) Assign(attrs ...field.AssignExpr) IPromptUsageFeedbackRecordDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promptUsageFeedbackRecordDo) Joins(fields ...field.RelationField) IPromptUsageFeedbackRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promptUsageFeedbackRecordDo) Preload(fields ...field.RelationField) IPromptUsageFeedbackRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promptUsageFeedbackRecordDo) FirstOrInit() (*model.PromptUsageFeedbackRecord, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptUsageFeedbackRecord), nil
	}
}

func (p promptUsageFeedbackRecordDo) FirstOrCreate() (*model.PromptUsageFeedbackRecord, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptUsageFeedbackRecord), nil
	}
}

func (p promptUsageFeedbackRecordDo) FindByPage(offset int, limit int) (result []*model.PromptUsageFeedbackRecord, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promptUsageFeedbackRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promptUsageFeedbackRecordDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promptUsageFeedbackRecordDo) Delete(models ...*model.PromptUsageFeedbackRecord) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promptUsageFeedbackRecordDo) withDO(do gen.Dao) *promptUsageFeedbackRecordDo {
	p.DO = *do.(*gen.DO)
	return p
}
