// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newPromptAssetRecord(db *gorm.DB, opts ...gen.DOOption) promptAssetRecord {
	_promptAssetRecord := promptAssetRecord{}

	_promptAssetRecord.promptAssetRecordDo.UseDB(db, opts...)
	_promptAssetRecord.promptAssetRecordDo.UseModel(&model.PromptAssetRecord{})

	tableName := _promptAssetRecord.promptAssetRecordDo.TableName()
	_promptAssetRecord.ALL = field.NewAsterisk(tableName)
	_promptAssetRecord.PromptAssetID = field.NewString(tableName, "prompt_asset_id")
	_promptAssetRecord.SchemaVersion = field.NewString(tableName, "schema_version")
	_promptAssetRecord.Title = field.NewString(tableName, "title")
	_promptAssetRecord.Domain = field.NewString(tableName, "domain")
	_promptAssetRecord.Lifecycle = field.NewString(tableName, "lifecycle")
	_promptAssetRecord.Permission = field.NewString(tableName, "permission")
	_promptAssetRecord.OwnerProject = field.NewString(tableName, "owner_project")
	_promptAssetRecord.CurrentVersionID = field.NewString(tableName, "current_version_id")
	_promptAssetRecord.PromptTemplateHash = field.NewString(tableName, "prompt_template_hash")
	_promptAssetRecord.TagsJSON = field.NewString(tableName, "tags_json")
	_promptAssetRecord.CreatedAt = field.NewString(tableName, "created_at")
	_promptAssetRecord.UpdatedAt = field.NewString(tableName, "updated_at")

	_promptAssetRecord.fillFieldMap()

	return _promptAssetRecord
}

type promptAssetRecord struct {
	promptAssetRecordDo

	ALL                field.Asterisk
	PromptAssetID      field.String
	SchemaVersion      field.String
	Title              field.String
	Domain             field.String
	Lifecycle          field.String
	Permission         field.String
	OwnerProject       field.String
	CurrentVersionID   field.String
	PromptTemplateHash field.String
	TagsJSON           field.String
	CreatedAt          field.String
	UpdatedAt          field.String

	fieldMap map[string]field.Expr
}

func (p promptAssetRecord) Table(newTableName string) *promptAssetRecord {
	p.promptAssetRecordDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promptAssetRecord) As(alias string) *promptAssetRecord {
	p.promptAssetRecordDo.DO = *(p.promptAssetRecordDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promptAssetRecord) updateTableName(table string) *promptAssetRecord {
	p.ALL = field.NewAsterisk(table)
	p.PromptAssetID = field.NewString(table, "prompt_asset_id")
	p.SchemaVersion = field.NewString(table, "schema_version")
	p.Title = field.NewString(table, "title")
	p.Domain = field.NewString(table, "domain")
	p.Lifecycle = field.NewString(table, "lifecycle")
	p.Permission = field.NewString(table, "permission")
	p.OwnerProject = field.NewString(table, "owner_project")
	p.CurrentVersionID = field.NewString(table, "current_version_id")
	p.PromptTemplateHash = field.NewString(table, "prompt_template_hash")
	p.TagsJSON = field.NewString(table, "tags_json")
	p.CreatedAt = field.NewString(table, "created_at")
	p.UpdatedAt = field.NewString(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *promptAssetRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promptAssetRecord) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 12)
	p.fieldMap["prompt_asset_id"] = p.PromptAssetID
	p.fieldMap["schema_version"] = p.SchemaVersion
	p.fieldMap["title"] = p.Title
	p.fieldMap["domain"] = p.Domain
	p.fieldMap["lifecycle"] = p.Lifecycle
	p.fieldMap["permission"] = p.Permission
	p.fieldMap["owner_project"] = p.OwnerProject
	p.fieldMap["current_version_id"] = p.CurrentVersionID
	p.fieldMap["prompt_template_hash"] = p.PromptTemplateHash
	p.fieldMap["tags_json"] = p.TagsJSON
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p promptAssetRecord) clone(db *gorm.DB) promptAssetRecord {
	p.promptAssetRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promptAssetRecord) replaceDB(db *gorm.DB) promptAssetRecord {
	p.promptAssetRecordDo.ReplaceDB(db)
	return p
}

type promptAssetRecordDo struct{ gen.DO }

type IPromptAssetRecordDo interface {
	gen.SubQuery
	Debug() IPromptAssetRecordDo
	WithContext(ctx context.Context) IPromptAssetRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromptAssetRecordDo
	WriteDB() IPromptAssetRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromptAssetRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromptAssetRecordDo
	Not(conds ...gen.Condition) IPromptAssetRecordDo
	Or(conds ...gen.Condition) IPromptAssetRecordDo
	Select(conds ...field.Expr) IPromptAssetRecordDo
	Where(conds ...gen.Condition) IPromptAssetRecordDo
	Order(conds ...field.Expr) IPromptAssetRecordDo
	Distinct(cols ...field.Expr) IPromptAssetRecordDo
	Omit(cols ...field.Expr) IPromptAssetRecordDo
	Join(table schema.Tabler, on ...field.Expr) IPromptAssetRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromptAssetRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromptAssetRecordDo
	Group(cols ...field.Expr) IPromptAssetRecordDo
	Having(conds ...gen.Condition) IPromptAssetRecordDo
	Limit(limit int) IPromptAssetRecordDo
	Offset(offset int) IPromptAssetRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromptAssetRecordDo
	Unscoped() IPromptAssetRecordDo
	Create(values ...*model.PromptAssetRecord) error
	CreateInBatches(values []*model.PromptAssetRecord, batchSize int) error
	Save(values ...*model.PromptAssetRecord) error
	First() (*model.PromptAssetRecord, error)
	Take() (*model.PromptAssetRecord, error)
	Last() (*model.PromptAssetRecord, error)
	Find() ([]*model.PromptAssetRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PromptAssetRecord, err error)
	FindInBatches(result *[]*model.PromptAssetRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PromptAssetRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromptAssetRecordDo
	Assign(attrs ...field.AssignExpr) IPromptAssetRecordDo
	Joins(fields ...field.RelationField) IPromptAssetRecordDo
	Preload(fields ...field.RelationField) IPromptAssetRecordDo
	FirstOrInit() (*model.PromptAssetRecord, error)
	FirstOrCreate() (*model.PromptAssetRecord, error)
	FindByPage(offset int, limit int) (result []*model.PromptAssetRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromptAssetRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promptAssetRecordDo) Debug() IPromptAssetRecordDo {
	return p.withDO(p.DO.Debug())
}

func (p promptAssetRecordDo) WithContext(ctx context.Context) IPromptAssetRecordDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promptAssetRecordDo) ReadDB() IPromptAssetRecordDo {
	return p.Clauses(dbresolver.Read)
}

func (p promptAssetRecordDo) WriteDB() IPromptAssetRecordDo {
	return p.Clauses(dbresolver.Write)
}

func (p promptAssetRecordDo) Session(config *gorm.Session) IPromptAssetRecordDo {
	return p.withDO(p.DO.Session(config))
}

func (p promptAssetRecordDo) Clauses(conds ...clause.Expression) IPromptAssetRecordDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promptAssetRecordDo) Returning(value interface{}, columns ...string) IPromptAssetRecordDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promptAssetRecordDo) Not(conds ...gen.Condition) IPromptAssetRecordDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promptAssetRecordDo) Or(conds ...gen.Condition) IPromptAssetRecordDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promptAssetRecordDo) Select(conds ...field.Expr) IPromptAssetRecordDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promptAssetRecordDo) Where(conds ...gen.Condition) IPromptAssetRecordDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promptAssetRecordDo) Order(conds ...field.Expr) IPromptAssetRecordDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promptAssetRecordDo) Distinct(cols ...field.Expr) IPromptAssetRecordDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promptAssetRecordDo) Omit(cols ...field.Expr) IPromptAssetRecordDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promptAssetRecordDo) Join(table schema.Tabler, on ...field.Expr) IPromptAssetRecordDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promptAssetRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromptAssetRecordDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promptAssetRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromptAssetRecordDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promptAssetRecordDo) Group(cols ...field.Expr) IPromptAssetRecordDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promptAssetRecordDo) Having(conds ...gen.Condition) IPromptAssetRecordDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promptAssetRecordDo) Limit(limit int) IPromptAssetRecordDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promptAssetRecordDo) Offset(offset int) IPromptAssetRecordDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promptAssetRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromptAssetRecordDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promptAssetRecordDo) Unscoped() IPromptAssetRecordDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promptAssetRecordDo) Create(values ...*model.PromptAssetRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promptAssetRecordDo) CreateInBatches(values []*model.PromptAssetRecord, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promptAssetRecordDo) Save(values ...*model.PromptAssetRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promptAssetRecordDo) First() (*model.PromptAssetRecord, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetRecord), nil
	}
}

func (p promptAssetRecordDo) Take() (*model.PromptAssetRecord, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetRecord), nil
	}
}

func (p promptAssetRecordDo) Last() (*model.PromptAssetRecord, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetRecord), nil
	}
}

func (p promptAssetRecordDo) Find() ([]*model.PromptAssetRecord, error) {
	result, err := p.DO.Find()
	return result.([]*model.PromptAssetRecord), err
}

func (p promptAssetRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PromptAssetRecord, err error) {
	buf := make([]*model.PromptAssetRecord, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promptAssetRecordDo) FindInBatches(result *[]*model.PromptAssetRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promptAssetRecordDo) Attrs(attrs ...field.AssignExpr) IPromptAssetRecordDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promptAssetRecordDo) Assign(attrs ...field.AssignExpr) IPromptAssetRecordDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promptAssetRecordDo) Joins(fields ...field.RelationField) IPromptAssetRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promptAssetRecordDo) Preload(fields ...field.RelationField) IPromptAssetRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promptAssetRecordDo) FirstOrInit() (*model.PromptAssetRecord, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetRecord), nil
	}
}

func (p promptAssetRecordDo) FirstOrCreate() (*model.PromptAssetRecord, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetRecord), nil
	}
}

func (p promptAssetRecordDo) FindByPage(offset int, limit int) (result []*model.PromptAssetRecord, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promptAssetRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promptAssetRecordDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promptAssetRecordDo) Delete(models ...*model.PromptAssetRecord) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promptAssetRecordDo) withDO(do gen.Dao) *promptAssetRecordDo {
	p.DO = *do.(*gen.DO)
	return p
}
