// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newPromptAssetSourceRefRecord(db *gorm.DB, opts ...gen.DOOption) promptAssetSourceRefRecord {
	_promptAssetSourceRefRecord := promptAssetSourceRefRecord{}

	_promptAssetSourceRefRecord.promptAssetSourceRefRecordDo.UseDB(db, opts...)
	_promptAssetSourceRefRecord.promptAssetSourceRefRecordDo.UseModel(&model.PromptAssetSourceRefRecord{})

	tableName := _promptAssetSourceRefRecord.promptAssetSourceRefRecordDo.TableName()
	_promptAssetSourceRefRecord.ALL = field.NewAsterisk(tableName)
	_promptAssetSourceRefRecord.ID = field.NewUint(tableName, "id")
	_promptAssetSourceRefRecord.PromptAssetID = field.NewString(tableName, "prompt_asset_id")
	_promptAssetSourceRefRecord.VersionID = field.NewString(tableName, "version_id")
	_promptAssetSourceRefRecord.URI = field.NewString(tableName, "uri")
	_promptAssetSourceRefRecord.Label = field.NewString(tableName, "label")
	_promptAssetSourceRefRecord.Evidence = field.NewString(tableName, "evidence")

	_promptAssetSourceRefRecord.fillFieldMap()

	return _promptAssetSourceRefRecord
}

type promptAssetSourceRefRecord struct {
	promptAssetSourceRefRecordDo

	ALL           field.Asterisk
	ID            field.Uint
	PromptAssetID field.String
	VersionID     field.String
	URI           field.String
	Label         field.String
	Evidence      field.String

	fieldMap map[string]field.Expr
}

func (p promptAssetSourceRefRecord) Table(newTableName string) *promptAssetSourceRefRecord {
	p.promptAssetSourceRefRecordDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promptAssetSourceRefRecord) As(alias string) *promptAssetSourceRefRecord {
	p.promptAssetSourceRefRecordDo.DO = *(p.promptAssetSourceRefRecordDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promptAssetSourceRefRecord) updateTableName(table string) *promptAssetSourceRefRecord {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.PromptAssetID = field.NewString(table, "prompt_asset_id")
	p.VersionID = field.NewString(table, "version_id")
	p.URI = field.NewString(table, "uri")
	p.Label = field.NewString(table, "label")
	p.Evidence = field.NewString(table, "evidence")

	p.fillFieldMap()

	return p
}

func (p *promptAssetSourceRefRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promptAssetSourceRefRecord) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 6)
	p.fieldMap["id"] = p.ID
	p.fieldMap["prompt_asset_id"] = p.PromptAssetID
	p.fieldMap["version_id"] = p.VersionID
	p.fieldMap["uri"] = p.URI
	p.fieldMap["label"] = p.Label
	p.fieldMap["evidence"] = p.Evidence
}

func (p promptAssetSourceRefRecord) clone(db *gorm.DB) promptAssetSourceRefRecord {
	p.promptAssetSourceRefRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promptAssetSourceRefRecord) replaceDB(db *gorm.DB) promptAssetSourceRefRecord {
	p.promptAssetSourceRefRecordDo.ReplaceDB(db)
	return p
}

type promptAssetSourceRefRecordDo struct{ gen.DO }

type IPromptAssetSourceRefRecordDo interface {
	gen.SubQuery
	Debug() IPromptAssetSourceRefRecordDo
	WithContext(ctx context.Context) IPromptAssetSourceRefRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromptAssetSourceRefRecordDo
	WriteDB() IPromptAssetSourceRefRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromptAssetSourceRefRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromptAssetSourceRefRecordDo
	Not(conds ...gen.Condition) IPromptAssetSourceRefRecordDo
	Or(conds ...gen.Condition) IPromptAssetSourceRefRecordDo
	Select(conds ...field.Expr) IPromptAssetSourceRefRecordDo
	Where(conds ...gen.Condition) IPromptAssetSourceRefRecordDo
	Order(conds ...field.Expr) IPromptAssetSourceRefRecordDo
	Distinct(cols ...field.Expr) IPromptAssetSourceRefRecordDo
	Omit(cols ...field.Expr) IPromptAssetSourceRefRecordDo
	Join(table schema.Tabler, on ...field.Expr) IPromptAssetSourceRefRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromptAssetSourceRefRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromptAssetSourceRefRecordDo
	Group(cols ...field.Expr) IPromptAssetSourceRefRecordDo
	Having(conds ...gen.Condition) IPromptAssetSourceRefRecordDo
	Limit(limit int) IPromptAssetSourceRefRecordDo
	Offset(offset int) IPromptAssetSourceRefRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromptAssetSourceRefRecordDo
	Unscoped() IPromptAssetSourceRefRecordDo
	Create(values ...*model.PromptAssetSourceRefRecord) error
	CreateInBatches(values []*model.PromptAssetSourceRefRecord, batchSize int) error
	Save(values ...*model.PromptAssetSourceRefRecord) error
	First() (*model.PromptAssetSourceRefRecord, error)
	Take() (*model.PromptAssetSourceRefRecord, error)
	Last() (*model.PromptAssetSourceRefRecord, error)
	Find() ([]*model.PromptAssetSourceRefRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PromptAssetSourceRefRecord, err error)
	FindInBatches(result *[]*model.PromptAssetSourceRefRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PromptAssetSourceRefRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromptAssetSourceRefRecordDo
	Assign(attrs ...field.AssignExpr) IPromptAssetSourceRefRecordDo
	Joins(fields ...field.RelationField) IPromptAssetSourceRefRecordDo
	Preload(fields ...field.RelationField) IPromptAssetSourceRefRecordDo
	FirstOrInit() (*model.PromptAssetSourceRefRecord, error)
	FirstOrCreate() (*model.PromptAssetSourceRefRecord, error)
	FindByPage(offset int, limit int) (result []*model.PromptAssetSourceRefRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromptAssetSourceRefRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promptAssetSourceRefRecordDo) Debug() IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Debug())
}

func (p promptAssetSourceRefRecordDo) WithContext(ctx context.Context) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promptAssetSourceRefRecordDo) ReadDB() IPromptAssetSourceRefRecordDo {
	return p.Clauses(dbresolver.Read)
}

func (p promptAssetSourceRefRecordDo) WriteDB() IPromptAssetSourceRefRecordDo {
	return p.Clauses(dbresolver.Write)
}

func (p promptAssetSourceRefRecordDo) Session(config *gorm.Session) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Session(config))
}

func (p promptAssetSourceRefRecordDo) Clauses(conds ...clause.Expression) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promptAssetSourceRefRecordDo) Returning(value interface{}, columns ...string) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promptAssetSourceRefRecordDo) Not(conds ...gen.Condition) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promptAssetSourceRefRecordDo) Or(conds ...gen.Condition) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promptAssetSourceRefRecordDo) Select(conds ...field.Expr) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promptAssetSourceRefRecordDo) Where(conds ...gen.Condition) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promptAssetSourceRefRecordDo) Order(conds ...field.Expr) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promptAssetSourceRefRecordDo) Distinct(cols ...field.Expr) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promptAssetSourceRefRecordDo) Omit(cols ...field.Expr) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promptAssetSourceRefRecordDo) Join(table schema.Tabler, on ...field.Expr) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promptAssetSourceRefRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promptAssetSourceRefRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promptAssetSourceRefRecordDo) Group(cols ...field.Expr) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promptAssetSourceRefRecordDo) Having(conds ...gen.Condition) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promptAssetSourceRefRecordDo) Limit(limit int) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promptAssetSourceRefRecordDo) Offset(offset int) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promptAssetSourceRefRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promptAssetSourceRefRecordDo) Unscoped() IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promptAssetSourceRefRecordDo) Create(values ...*model.PromptAssetSourceRefRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promptAssetSourceRefRecordDo) CreateInBatches(values []*model.PromptAssetSourceRefRecord, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promptAssetSourceRefRecordDo) Save(values ...*model.PromptAssetSourceRefRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promptAssetSourceRefRecordDo) First() (*model.PromptAssetSourceRefRecord, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetSourceRefRecord), nil
	}
}

func (p promptAssetSourceRefRecordDo) Take() (*model.PromptAssetSourceRefRecord, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetSourceRefRecord), nil
	}
}

func (p promptAssetSourceRefRecordDo) Last() (*model.PromptAssetSourceRefRecord, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetSourceRefRecord), nil
	}
}

func (p promptAssetSourceRefRecordDo) Find() ([]*model.PromptAssetSourceRefRecord, error) {
	result, err := p.DO.Find()
	return result.([]*model.PromptAssetSourceRefRecord), err
}

func (p promptAssetSourceRefRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PromptAssetSourceRefRecord, err error) {
	buf := make([]*model.PromptAssetSourceRefRecord, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promptAssetSourceRefRecordDo) FindInBatches(result *[]*model.PromptAssetSourceRefRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promptAssetSourceRefRecordDo) Attrs(attrs ...field.AssignExpr) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promptAssetSourceRefRecordDo) Assign(attrs ...field.AssignExpr) IPromptAssetSourceRefRecordDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promptAssetSourceRefRecordDo) Joins(fields ...field.RelationField) IPromptAssetSourceRefRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promptAssetSourceRefRecordDo) Preload(fields ...field.RelationField) IPromptAssetSourceRefRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promptAssetSourceRefRecordDo) FirstOrInit() (*model.PromptAssetSourceRefRecord, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetSourceRefRecord), nil
	}
}

func (p promptAssetSourceRefRecordDo) FirstOrCreate() (*model.PromptAssetSourceRefRecord, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PromptAssetSourceRefRecord), nil
	}
}

func (p promptAssetSourceRefRecordDo) FindByPage(offset int, limit int) (result []*model.PromptAssetSourceRefRecord, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promptAssetSourceRefRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promptAssetSourceRefRecordDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promptAssetSourceRefRecordDo) Delete(models ...*model.PromptAssetSourceRefRecord) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promptAssetSourceRefRecordDo) withDO(do gen.Dao) *promptAssetSourceRefRecordDo {
	p.DO = *do.(*gen.DO)
	return p
}
