// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newPropertyValueRecord(db *gorm.DB, opts ...gen.DOOption) propertyValueRecord {
	_propertyValueRecord := propertyValueRecord{}

	_propertyValueRecord.propertyValueRecordDo.UseDB(db, opts...)
	_propertyValueRecord.propertyValueRecordDo.UseModel(&model.PropertyValueRecord{})

	tableName := _propertyValueRecord.propertyValueRecordDo.TableName()
	_propertyValueRecord.ALL = field.NewAsterisk(tableName)
	_propertyValueRecord.ID = field.NewUint(tableName, "id")
	_propertyValueRecord.NotePath = field.NewString(tableName, "note_path")
	_propertyValueRecord.Name = field.NewString(tableName, "name")
	_propertyValueRecord.Type = field.NewString(tableName, "type")
	_propertyValueRecord.Raw = field.NewString(tableName, "raw")
	_propertyValueRecord.Value = field.NewString(tableName, "value")
	_propertyValueRecord.Source = field.NewString(tableName, "source")

	_propertyValueRecord.fillFieldMap()

	return _propertyValueRecord
}

type propertyValueRecord struct {
	propertyValueRecordDo

	ALL      field.Asterisk
	ID       field.Uint
	NotePath field.String
	Name     field.String
	Type     field.String
	Raw      field.String
	Value    field.String
	Source   field.String

	fieldMap map[string]field.Expr
}

func (p propertyValueRecord) Table(newTableName string) *propertyValueRecord {
	p.propertyValueRecordDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p propertyValueRecord) As(alias string) *propertyValueRecord {
	p.propertyValueRecordDo.DO = *(p.propertyValueRecordDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *propertyValueRecord) updateTableName(table string) *propertyValueRecord {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.NotePath = field.NewString(table, "note_path")
	p.Name = field.NewString(table, "name")
	p.Type = field.NewString(table, "type")
	p.Raw = field.NewString(table, "raw")
	p.Value = field.NewString(table, "value")
	p.Source = field.NewString(table, "source")

	p.fillFieldMap()

	return p
}

func (p *propertyValueRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *propertyValueRecord) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["id"] = p.ID
	p.fieldMap["note_path"] = p.NotePath
	p.fieldMap["name"] = p.Name
	p.fieldMap["type"] = p.Type
	p.fieldMap["raw"] = p.Raw
	p.fieldMap["value"] = p.Value
	p.fieldMap["source"] = p.Source
}

func (p propertyValueRecord) clone(db *gorm.DB) propertyValueRecord {
	p.propertyValueRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p propertyValueRecord) replaceDB(db *gorm.DB) propertyValueRecord {
	p.propertyValueRecordDo.ReplaceDB(db)
	return p
}

type propertyValueRecordDo struct{ gen.DO }

type IPropertyValueRecordDo interface {
	gen.SubQuery
	Debug() IPropertyValueRecordDo
	WithContext(ctx context.Context) IPropertyValueRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPropertyValueRecordDo
	WriteDB() IPropertyValueRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPropertyValueRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPropertyValueRecordDo
	Not(conds ...gen.Condition) IPropertyValueRecordDo
	Or(conds ...gen.Condition) IPropertyValueRecordDo
	Select(conds ...field.Expr) IPropertyValueRecordDo
	Where(conds ...gen.Condition) IPropertyValueRecordDo
	Order(conds ...field.Expr) IPropertyValueRecordDo
	Distinct(cols ...field.Expr) IPropertyValueRecordDo
	Omit(cols ...field.Expr) IPropertyValueRecordDo
	Join(table schema.Tabler, on ...field.Expr) IPropertyValueRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPropertyValueRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPropertyValueRecordDo
	Group(cols ...field.Expr) IPropertyValueRecordDo
	Having(conds ...gen.Condition) IPropertyValueRecordDo
	Limit(limit int) IPropertyValueRecordDo
	Offset(offset int) IPropertyValueRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPropertyValueRecordDo
	Unscoped() IPropertyValueRecordDo
	Create(values ...*model.PropertyValueRecord) error
	CreateInBatches(values []*model.PropertyValueRecord, batchSize int) error
	Save(values ...*model.PropertyValueRecord) error
	First() (*model.PropertyValueRecord, error)
	Take() (*model.PropertyValueRecord, error)
	Last() (*model.PropertyValueRecord, error)
	Find() ([]*model.PropertyValueRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PropertyValueRecord, err error)
	FindInBatches(result *[]*model.PropertyValueRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PropertyValueRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPropertyValueRecordDo
	Assign(attrs ...field.AssignExpr) IPropertyValueRecordDo
	Joins(fields ...field.RelationField) IPropertyValueRecordDo
	Preload(fields ...field.RelationField) IPropertyValueRecordDo
	FirstOrInit() (*model.PropertyValueRecord, error)
	FirstOrCreate() (*model.PropertyValueRecord, error)
	FindByPage(offset int, limit int) (result []*model.PropertyValueRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPropertyValueRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p propertyValueRecordDo) Debug() IPropertyValueRecordDo {
	return p.withDO(p.DO.Debug())
}

func (p propertyValueRecordDo) WithContext(ctx context.Context) IPropertyValueRecordDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p propertyValueRecordDo) ReadDB() IPropertyValueRecordDo {
	return p.Clauses(dbresolver.Read)
}

func (p propertyValueRecordDo) WriteDB() IPropertyValueRecordDo {
	return p.Clauses(dbresolver.Write)
}

func (p propertyValueRecordDo) Session(config *gorm.Session) IPropertyValueRecordDo {
	return p.withDO(p.DO.Session(config))
}

func (p propertyValueRecordDo) Clauses(conds ...clause.Expression) IPropertyValueRecordDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p propertyValueRecordDo) Returning(value interface{}, columns ...string) IPropertyValueRecordDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p propertyValueRecordDo) Not(conds ...gen.Condition) IPropertyValueRecordDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p propertyValueRecordDo) Or(conds ...gen.Condition) IPropertyValueRecordDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p propertyValueRecordDo) Select(conds ...field.Expr) IPropertyValueRecordDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p propertyValueRecordDo) Where(conds ...gen.Condition) IPropertyValueRecordDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p propertyValueRecordDo) Order(conds ...field.Expr) IPropertyValueRecordDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p propertyValueRecordDo) Distinct(cols ...field.Expr) IPropertyValueRecordDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p propertyValueRecordDo) Omit(cols ...field.Expr) IPropertyValueRecordDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p propertyValueRecordDo) Join(table schema.Tabler, on ...field.Expr) IPropertyValueRecordDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p propertyValueRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPropertyValueRecordDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p propertyValueRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IPropertyValueRecordDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p propertyValueRecordDo) Group(cols ...field.Expr) IPropertyValueRecordDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p propertyValueRecordDo) Having(conds ...gen.Condition) IPropertyValueRecordDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p propertyValueRecordDo) Limit(limit int) IPropertyValueRecordDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p propertyValueRecordDo) Offset(offset int) IPropertyValueRecordDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p propertyValueRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPropertyValueRecordDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p propertyValueRecordDo) Unscoped() IPropertyValueRecordDo {
	return p.withDO(p.DO.Unscoped())
}

func (p propertyValueRecordDo) Create(values ...*model.PropertyValueRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p propertyValueRecordDo) CreateInBatches(values []*model.PropertyValueRecord, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p propertyValueRecordDo) Save(values ...*model.PropertyValueRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p propertyValueRecordDo) First() (*model.PropertyValueRecord, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyValueRecord), nil
	}
}

func (p propertyValueRecordDo) Take() (*model.PropertyValueRecord, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyValueRecord), nil
	}
}

func (p propertyValueRecordDo) Last() (*model.PropertyValueRecord, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyValueRecord), nil
	}
}

func (p propertyValueRecordDo) Find() ([]*model.PropertyValueRecord, error) {
	result, err := p.DO.Find()
	return result.([]*model.PropertyValueRecord), err
}

func (p propertyValueRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PropertyValueRecord, err error) {
	buf := make([]*model.PropertyValueRecord, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p propertyValueRecordDo) FindInBatches(result *[]*model.PropertyValueRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p propertyValueRecordDo) Attrs(attrs ...field.AssignExpr) IPropertyValueRecordDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p propertyValueRecordDo) Assign(attrs ...field.AssignExpr) IPropertyValueRecordDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p propertyValueRecordDo) Joins(fields ...field.RelationField) IPropertyValueRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p propertyValueRecordDo) Preload(fields ...field.RelationField) IPropertyValueRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p propertyValueRecordDo) FirstOrInit() (*model.PropertyValueRecord, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyValueRecord), nil
	}
}

func (p propertyValueRecordDo) FirstOrCreate() (*model.PropertyValueRecord, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyValueRecord), nil
	}
}

func (p propertyValueRecordDo) FindByPage(offset int, limit int) (result []*model.PropertyValueRecord, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p propertyValueRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p propertyValueRecordDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p propertyValueRecordDo) Delete(models ...*model.PropertyValueRecord) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *propertyValueRecordDo) withDO(do gen.Dao) *propertyValueRecordDo {
	p.DO = *do.(*gen.DO)
	return p
}
