// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newPropertyDefinitionRecord(db *gorm.DB, opts ...gen.DOOption) propertyDefinitionRecord {
	_propertyDefinitionRecord := propertyDefinitionRecord{}

	_propertyDefinitionRecord.propertyDefinitionRecordDo.UseDB(db, opts...)
	_propertyDefinitionRecord.propertyDefinitionRecordDo.UseModel(&model.PropertyDefinitionRecord{})

	tableName := _propertyDefinitionRecord.propertyDefinitionRecordDo.TableName()
	_propertyDefinitionRecord.ALL = field.NewAsterisk(tableName)
	_propertyDefinitionRecord.Name = field.NewString(tableName, "name")
	_propertyDefinitionRecord.Type = field.NewString(tableName, "type")
	_propertyDefinitionRecord.Source = field.NewString(tableName, "source")
	_propertyDefinitionRecord.Count_ = field.NewInt(tableName, "count")
	_propertyDefinitionRecord.Samples = field.NewString(tableName, "samples")

	_propertyDefinitionRecord.fillFieldMap()

	return _propertyDefinitionRecord
}

type propertyDefinitionRecord struct {
	propertyDefinitionRecordDo

	ALL     field.Asterisk
	Name    field.String
	Type    field.String
	Source  field.String
	Count_  field.Int
	Samples field.String

	fieldMap map[string]field.Expr
}

func (p propertyDefinitionRecord) Table(newTableName string) *propertyDefinitionRecord {
	p.propertyDefinitionRecordDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p propertyDefinitionRecord) As(alias string) *propertyDefinitionRecord {
	p.propertyDefinitionRecordDo.DO = *(p.propertyDefinitionRecordDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *propertyDefinitionRecord) updateTableName(table string) *propertyDefinitionRecord {
	p.ALL = field.NewAsterisk(table)
	p.Name = field.NewString(table, "name")
	p.Type = field.NewString(table, "type")
	p.Source = field.NewString(table, "source")
	p.Count_ = field.NewInt(table, "count")
	p.Samples = field.NewString(table, "samples")

	p.fillFieldMap()

	return p
}

func (p *propertyDefinitionRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *propertyDefinitionRecord) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["name"] = p.Name
	p.fieldMap["type"] = p.Type
	p.fieldMap["source"] = p.Source
	p.fieldMap["count"] = p.Count_
	p.fieldMap["samples"] = p.Samples
}

func (p propertyDefinitionRecord) clone(db *gorm.DB) propertyDefinitionRecord {
	p.propertyDefinitionRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p propertyDefinitionRecord) replaceDB(db *gorm.DB) propertyDefinitionRecord {
	p.propertyDefinitionRecordDo.ReplaceDB(db)
	return p
}

type propertyDefinitionRecordDo struct{ gen.DO }

type IPropertyDefinitionRecordDo interface {
	gen.SubQuery
	Debug() IPropertyDefinitionRecordDo
	WithContext(ctx context.Context) IPropertyDefinitionRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPropertyDefinitionRecordDo
	WriteDB() IPropertyDefinitionRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPropertyDefinitionRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPropertyDefinitionRecordDo
	Not(conds ...gen.Condition) IPropertyDefinitionRecordDo
	Or(conds ...gen.Condition) IPropertyDefinitionRecordDo
	Select(conds ...field.Expr) IPropertyDefinitionRecordDo
	Where(conds ...gen.Condition) IPropertyDefinitionRecordDo
	Order(conds ...field.Expr) IPropertyDefinitionRecordDo
	Distinct(cols ...field.Expr) IPropertyDefinitionRecordDo
	Omit(cols ...field.Expr) IPropertyDefinitionRecordDo
	Join(table schema.Tabler, on ...field.Expr) IPropertyDefinitionRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPropertyDefinitionRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPropertyDefinitionRecordDo
	Group(cols ...field.Expr) IPropertyDefinitionRecordDo
	Having(conds ...gen.Condition) IPropertyDefinitionRecordDo
	Limit(limit int) IPropertyDefinitionRecordDo
	Offset(offset int) IPropertyDefinitionRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPropertyDefinitionRecordDo
	Unscoped() IPropertyDefinitionRecordDo
	Create(values ...*model.PropertyDefinitionRecord) error
	CreateInBatches(values []*model.PropertyDefinitionRecord, batchSize int) error
	Save(values ...*model.PropertyDefinitionRecord) error
	First() (*model.PropertyDefinitionRecord, error)
	Take() (*model.PropertyDefinitionRecord, error)
	Last() (*model.PropertyDefinitionRecord, error)
	Find() ([]*model.PropertyDefinitionRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PropertyDefinitionRecord, err error)
	FindInBatches(result *[]*model.PropertyDefinitionRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PropertyDefinitionRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPropertyDefinitionRecordDo
	Assign(attrs ...field.AssignExpr) IPropertyDefinitionRecordDo
	Joins(fields ...field.RelationField) IPropertyDefinitionRecordDo
	Preload(fields ...field.RelationField) IPropertyDefinitionRecordDo
	FirstOrInit() (*model.PropertyDefinitionRecord, error)
	FirstOrCreate() (*model.PropertyDefinitionRecord, error)
	FindByPage(offset int, limit int) (result []*model.PropertyDefinitionRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPropertyDefinitionRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p propertyDefinitionRecordDo) Debug() IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Debug())
}

func (p propertyDefinitionRecordDo) WithContext(ctx context.Context) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p propertyDefinitionRecordDo) ReadDB() IPropertyDefinitionRecordDo {
	return p.Clauses(dbresolver.Read)
}

func (p propertyDefinitionRecordDo) WriteDB() IPropertyDefinitionRecordDo {
	return p.Clauses(dbresolver.Write)
}

func (p propertyDefinitionRecordDo) Session(config *gorm.Session) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Session(config))
}

func (p propertyDefinitionRecordDo) Clauses(conds ...clause.Expression) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p propertyDefinitionRecordDo) Returning(value interface{}, columns ...string) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p propertyDefinitionRecordDo) Not(conds ...gen.Condition) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p propertyDefinitionRecordDo) Or(conds ...gen.Condition) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p propertyDefinitionRecordDo) Select(conds ...field.Expr) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p propertyDefinitionRecordDo) Where(conds ...gen.Condition) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p propertyDefinitionRecordDo) Order(conds ...field.Expr) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p propertyDefinitionRecordDo) Distinct(cols ...field.Expr) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p propertyDefinitionRecordDo) Omit(cols ...field.Expr) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p propertyDefinitionRecordDo) Join(table schema.Tabler, on ...field.Expr) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p propertyDefinitionRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p propertyDefinitionRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p propertyDefinitionRecordDo) Group(cols ...field.Expr) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p propertyDefinitionRecordDo) Having(conds ...gen.Condition) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p propertyDefinitionRecordDo) Limit(limit int) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p propertyDefinitionRecordDo) Offset(offset int) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p propertyDefinitionRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p propertyDefinitionRecordDo) Unscoped() IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Unscoped())
}

func (p propertyDefinitionRecordDo) Create(values ...*model.PropertyDefinitionRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p propertyDefinitionRecordDo) CreateInBatches(values []*model.PropertyDefinitionRecord, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p propertyDefinitionRecordDo) Save(values ...*model.PropertyDefinitionRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p propertyDefinitionRecordDo) First() (*model.PropertyDefinitionRecord, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyDefinitionRecord), nil
	}
}

func (p propertyDefinitionRecordDo) Take() (*model.PropertyDefinitionRecord, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyDefinitionRecord), nil
	}
}

func (p propertyDefinitionRecordDo) Last() (*model.PropertyDefinitionRecord, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyDefinitionRecord), nil
	}
}

func (p propertyDefinitionRecordDo) Find() ([]*model.PropertyDefinitionRecord, error) {
	result, err := p.DO.Find()
	return result.([]*model.PropertyDefinitionRecord), err
}

func (p propertyDefinitionRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PropertyDefinitionRecord, err error) {
	buf := make([]*model.PropertyDefinitionRecord, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p propertyDefinitionRecordDo) FindInBatches(result *[]*model.PropertyDefinitionRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p propertyDefinitionRecordDo) Attrs(attrs ...field.AssignExpr) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p propertyDefinitionRecordDo) Assign(attrs ...field.AssignExpr) IPropertyDefinitionRecordDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p propertyDefinitionRecordDo) Joins(fields ...field.RelationField) IPropertyDefinitionRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p propertyDefinitionRecordDo) Preload(fields ...field.RelationField) IPropertyDefinitionRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p propertyDefinitionRecordDo) FirstOrInit() (*model.PropertyDefinitionRecord, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyDefinitionRecord), nil
	}
}

func (p propertyDefinitionRecordDo) FirstOrCreate() (*model.PropertyDefinitionRecord, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyDefinitionRecord), nil
	}
}

func (p propertyDefinitionRecordDo) FindByPage(offset int, limit int) (result []*model.PropertyDefinitionRecord, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p propertyDefinitionRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p propertyDefinitionRecordDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p propertyDefinitionRecordDo) Delete(models ...*model.PropertyDefinitionRecord) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *propertyDefinitionRecordDo) withDO(do gen.Dao) *propertyDefinitionRecordDo {
	p.DO = *do.(*gen.DO)
	return p
}
