// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSearchTokenRecord(db *gorm.DB, opts ...gen.DOOption) searchTokenRecord {
	_searchTokenRecord := searchTokenRecord{}

	_searchTokenRecord.searchTokenRecordDo.UseDB(db, opts...)
	_searchTokenRecord.searchTokenRecordDo.UseModel(&model.SearchTokenRecord{})

	tableName := _searchTokenRecord.searchTokenRecordDo.TableName()
	_searchTokenRecord.ALL = field.NewAsterisk(tableName)
	_searchTokenRecord.ID = field.NewUint(tableName, "id")
	_searchTokenRecord.Token = field.NewString(tableName, "token")
	_searchTokenRecord.NotePath = field.NewString(tableName, "note_path")
	_searchTokenRecord.Field = field.NewString(tableName, "field")
	_searchTokenRecord.Count_ = field.NewInt(tableName, "count")
	_searchTokenRecord.Weight = field.NewInt(tableName, "weight")

	_searchTokenRecord.fillFieldMap()

	return _searchTokenRecord
}

type searchTokenRecord struct {
	searchTokenRecordDo

	ALL      field.Asterisk
	ID       field.Uint
	Token    field.String
	NotePath field.String
	Field    field.String
	Count_   field.Int
	Weight   field.Int

	fieldMap map[string]field.Expr
}

func (s searchTokenRecord) Table(newTableName string) *searchTokenRecord {
	s.searchTokenRecordDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s searchTokenRecord) As(alias string) *searchTokenRecord {
	s.searchTokenRecordDo.DO = *(s.searchTokenRecordDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *searchTokenRecord) updateTableName(table string) *searchTokenRecord {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint(table, "id")
	s.Token = field.NewString(table, "token")
	s.NotePath = field.NewString(table, "note_path")
	s.Field = field.NewString(table, "field")
	s.Count_ = field.NewInt(table, "count")
	s.Weight = field.NewInt(table, "weight")

	s.fillFieldMap()

	return s
}

func (s *searchTokenRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *searchTokenRecord) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["id"] = s.ID
	s.fieldMap["token"] = s.Token
	s.fieldMap["note_path"] = s.NotePath
	s.fieldMap["field"] = s.Field
	s.fieldMap["count"] = s.Count_
	s.fieldMap["weight"] = s.Weight
}

func (s searchTokenRecord) clone(db *gorm.DB) searchTokenRecord {
	s.searchTokenRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s searchTokenRecord) replaceDB(db *gorm.DB) searchTokenRecord {
	s.searchTokenRecordDo.ReplaceDB(db)
	return s
}

type searchTokenRecordDo struct{ gen.DO }

type ISearchTokenRecordDo interface {
	gen.SubQuery
	Debug() ISearchTokenRecordDo
	WithContext(ctx context.Context) ISearchTokenRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISearchTokenRecordDo
	WriteDB() ISearchTokenRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISearchTokenRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISearchTokenRecordDo
	Not(conds ...gen.Condition) ISearchTokenRecordDo
	Or(conds ...gen.Condition) ISearchTokenRecordDo
	Select(conds ...field.Expr) ISearchTokenRecordDo
	Where(conds ...gen.Condition) ISearchTokenRecordDo
	Order(conds ...field.Expr) ISearchTokenRecordDo
	Distinct(cols ...field.Expr) ISearchTokenRecordDo
	Omit(cols ...field.Expr) ISearchTokenRecordDo
	Join(table schema.Tabler, on ...field.Expr) ISearchTokenRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISearchTokenRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISearchTokenRecordDo
	Group(cols ...field.Expr) ISearchTokenRecordDo
	Having(conds ...gen.Condition) ISearchTokenRecordDo
	Limit(limit int) ISearchTokenRecordDo
	Offset(offset int) ISearchTokenRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISearchTokenRecordDo
	Unscoped() ISearchTokenRecordDo
	Create(values ...*model.SearchTokenRecord) error
	CreateInBatches(values []*model.SearchTokenRecord, batchSize int) error
	Save(values ...*model.SearchTokenRecord) error
	First() (*model.SearchTokenRecord, error)
	Take() (*model.SearchTokenRecord, error)
	Last() (*model.SearchTokenRecord, error)
	Find() ([]*model.SearchTokenRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SearchTokenRecord, err error)
	FindInBatches(result *[]*model.SearchTokenRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SearchTokenRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISearchTokenRecordDo
	Assign(attrs ...field.AssignExpr) ISearchTokenRecordDo
	Joins(fields ...field.RelationField) ISearchTokenRecordDo
	Preload(fields ...field.RelationField) ISearchTokenRecordDo
	FirstOrInit() (*model.SearchTokenRecord, error)
	FirstOrCreate() (*model.SearchTokenRecord, error)
	FindByPage(offset int, limit int) (result []*model.SearchTokenRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISearchTokenRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s searchTokenRecordDo) Debug() ISearchTokenRecordDo {
	return s.withDO(s.DO.Debug())
}

func (s searchTokenRecordDo) WithContext(ctx context.Context) ISearchTokenRecordDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s searchTokenRecordDo) ReadDB() ISearchTokenRecordDo {
	return s.Clauses(dbresolver.Read)
}

func (s searchTokenRecordDo) WriteDB() ISearchTokenRecordDo {
	return s.Clauses(dbresolver.Write)
}

func (s searchTokenRecordDo) Session(config *gorm.Session) ISearchTokenRecordDo {
	return s.withDO(s.DO.Session(config))
}

func (s searchTokenRecordDo) Clauses(conds ...clause.Expression) ISearchTokenRecordDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s searchTokenRecordDo) Returning(value interface{}, columns ...string) ISearchTokenRecordDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s searchTokenRecordDo) Not(conds ...gen.Condition) ISearchTokenRecordDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s searchTokenRecordDo) Or(conds ...gen.Condition) ISearchTokenRecordDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s searchTokenRecordDo) Select(conds ...field.Expr) ISearchTokenRecordDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s searchTokenRecordDo) Where(conds ...gen.Condition) ISearchTokenRecordDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s searchTokenRecordDo) Order(conds ...field.Expr) ISearchTokenRecordDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s searchTokenRecordDo) Distinct(cols ...field.Expr) ISearchTokenRecordDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s searchTokenRecordDo) Omit(cols ...field.Expr) ISearchTokenRecordDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s searchTokenRecordDo) Join(table schema.Tabler, on ...field.Expr) ISearchTokenRecordDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s searchTokenRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISearchTokenRecordDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s searchTokenRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) ISearchTokenRecordDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s searchTokenRecordDo) Group(cols ...field.Expr) ISearchTokenRecordDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s searchTokenRecordDo) Having(conds ...gen.Condition) ISearchTokenRecordDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s searchTokenRecordDo) Limit(limit int) ISearchTokenRecordDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s searchTokenRecordDo) Offset(offset int) ISearchTokenRecordDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s searchTokenRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISearchTokenRecordDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s searchTokenRecordDo) Unscoped() ISearchTokenRecordDo {
	return s.withDO(s.DO.Unscoped())
}

func (s searchTokenRecordDo) Create(values ...*model.SearchTokenRecord) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s searchTokenRecordDo) CreateInBatches(values []*model.SearchTokenRecord, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s searchTokenRecordDo) Save(values ...*model.SearchTokenRecord) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s searchTokenRecordDo) First() (*model.SearchTokenRecord, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SearchTokenRecord), nil
	}
}

func (s searchTokenRecordDo) Take() (*model.SearchTokenRecord, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SearchTokenRecord), nil
	}
}

func (s searchTokenRecordDo) Last() (*model.SearchTokenRecord, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SearchTokenRecord), nil
	}
}

func (s searchTokenRecordDo) Find() ([]*model.SearchTokenRecord, error) {
	result, err := s.DO.Find()
	return result.([]*model.SearchTokenRecord), err
}

func (s searchTokenRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SearchTokenRecord, err error) {
	buf := make([]*model.SearchTokenRecord, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s searchTokenRecordDo) FindInBatches(result *[]*model.SearchTokenRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s searchTokenRecordDo) Attrs(attrs ...field.AssignExpr) ISearchTokenRecordDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s searchTokenRecordDo) Assign(attrs ...field.AssignExpr) ISearchTokenRecordDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s searchTokenRecordDo) Joins(fields ...field.RelationField) ISearchTokenRecordDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s searchTokenRecordDo) Preload(fields ...field.RelationField) ISearchTokenRecordDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s searchTokenRecordDo) FirstOrInit() (*model.SearchTokenRecord, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SearchTokenRecord), nil
	}
}

func (s searchTokenRecordDo) FirstOrCreate() (*model.SearchTokenRecord, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SearchTokenRecord), nil
	}
}

func (s searchTokenRecordDo) FindByPage(offset int, limit int) (result []*model.SearchTokenRecord, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s searchTokenRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s searchTokenRecordDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s searchTokenRecordDo) Delete(models ...*model.SearchTokenRecord) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *searchTokenRecordDo) withDO(do gen.Dao) *searchTokenRecordDo {
	s.DO = *do.(*gen.DO)
	return s
}
