// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newTagRecord(db *gorm.DB, opts ...gen.DOOption) tagRecord {
	_tagRecord := tagRecord{}

	_tagRecord.tagRecordDo.UseDB(db, opts...)
	_tagRecord.tagRecordDo.UseModel(&model.TagRecord{})

	tableName := _tagRecord.tagRecordDo.TableName()
	_tagRecord.ALL = field.NewAsterisk(tableName)
	_tagRecord.ID = field.NewUint(tableName, "id")
	_tagRecord.NotePath = field.NewString(tableName, "note_path")
	_tagRecord.Tag = field.NewString(tableName, "tag")

	_tagRecord.fillFieldMap()

	return _tagRecord
}

type tagRecord struct {
	tagRecordDo

	ALL      field.Asterisk
	ID       field.Uint
	NotePath field.String
	Tag      field.String

	fieldMap map[string]field.Expr
}

func (t tagRecord) Table(newTableName string) *tagRecord {
	t.tagRecordDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tagRecord) As(alias string) *tagRecord {
	t.tagRecordDo.DO = *(t.tagRecordDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tagRecord) updateTableName(table string) *tagRecord {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewUint(table, "id")
	t.NotePath = field.NewString(table, "note_path")
	t.Tag = field.NewString(table, "tag")

	t.fillFieldMap()

	return t
}

func (t *tagRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tagRecord) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 3)
	t.fieldMap["id"] = t.ID
	t.fieldMap["note_path"] = t.NotePath
	t.fieldMap["tag"] = t.Tag
}

func (t tagRecord) clone(db *gorm.DB) tagRecord {
	t.tagRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tagRecord) replaceDB(db *gorm.DB) tagRecord {
	t.tagRecordDo.ReplaceDB(db)
	return t
}

type tagRecordDo struct{ gen.DO }

type ITagRecordDo interface {
	gen.SubQuery
	Debug() ITagRecordDo
	WithContext(ctx context.Context) ITagRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITagRecordDo
	WriteDB() ITagRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITagRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITagRecordDo
	Not(conds ...gen.Condition) ITagRecordDo
	Or(conds ...gen.Condition) ITagRecordDo
	Select(conds ...field.Expr) ITagRecordDo
	Where(conds ...gen.Condition) ITagRecordDo
	Order(conds ...field.Expr) ITagRecordDo
	Distinct(cols ...field.Expr) ITagRecordDo
	Omit(cols ...field.Expr) ITagRecordDo
	Join(table schema.Tabler, on ...field.Expr) ITagRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITagRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITagRecordDo
	Group(cols ...field.Expr) ITagRecordDo
	Having(conds ...gen.Condition) ITagRecordDo
	Limit(limit int) ITagRecordDo
	Offset(offset int) ITagRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITagRecordDo
	Unscoped() ITagRecordDo
	Create(values ...*model.TagRecord) error
	CreateInBatches(values []*model.TagRecord, batchSize int) error
	Save(values ...*model.TagRecord) error
	First() (*model.TagRecord, error)
	Take() (*model.TagRecord, error)
	Last() (*model.TagRecord, error)
	Find() ([]*model.TagRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TagRecord, err error)
	FindInBatches(result *[]*model.TagRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TagRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITagRecordDo
	Assign(attrs ...field.AssignExpr) ITagRecordDo
	Joins(fields ...field.RelationField) ITagRecordDo
	Preload(fields ...field.RelationField) ITagRecordDo
	FirstOrInit() (*model.TagRecord, error)
	FirstOrCreate() (*model.TagRecord, error)
	FindByPage(offset int, limit int) (result []*model.TagRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITagRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tagRecordDo) Debug() ITagRecordDo {
	return t.withDO(t.DO.Debug())
}

func (t tagRecordDo) WithContext(ctx context.Context) ITagRecordDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tagRecordDo) ReadDB() ITagRecordDo {
	return t.Clauses(dbresolver.Read)
}

func (t tagRecordDo) WriteDB() ITagRecordDo {
	return t.Clauses(dbresolver.Write)
}

func (t tagRecordDo) Session(config *gorm.Session) ITagRecordDo {
	return t.withDO(t.DO.Session(config))
}

func (t tagRecordDo) Clauses(conds ...clause.Expression) ITagRecordDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tagRecordDo) Returning(value interface{}, columns ...string) ITagRecordDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tagRecordDo) Not(conds ...gen.Condition) ITagRecordDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tagRecordDo) Or(conds ...gen.Condition) ITagRecordDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tagRecordDo) Select(conds ...field.Expr) ITagRecordDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tagRecordDo) Where(conds ...gen.Condition) ITagRecordDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tagRecordDo) Order(conds ...field.Expr) ITagRecordDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tagRecordDo) Distinct(cols ...field.Expr) ITagRecordDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tagRecordDo) Omit(cols ...field.Expr) ITagRecordDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tagRecordDo) Join(table schema.Tabler, on ...field.Expr) ITagRecordDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tagRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITagRecordDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tagRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) ITagRecordDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tagRecordDo) Group(cols ...field.Expr) ITagRecordDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tagRecordDo) Having(conds ...gen.Condition) ITagRecordDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tagRecordDo) Limit(limit int) ITagRecordDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tagRecordDo) Offset(offset int) ITagRecordDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tagRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITagRecordDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tagRecordDo) Unscoped() ITagRecordDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tagRecordDo) Create(values ...*model.TagRecord) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tagRecordDo) CreateInBatches(values []*model.TagRecord, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tagRecordDo) Save(values ...*model.TagRecord) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tagRecordDo) First() (*model.TagRecord, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagRecord), nil
	}
}

func (t tagRecordDo) Take() (*model.TagRecord, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagRecord), nil
	}
}

func (t tagRecordDo) Last() (*model.TagRecord, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagRecord), nil
	}
}

func (t tagRecordDo) Find() ([]*model.TagRecord, error) {
	result, err := t.DO.Find()
	return result.([]*model.TagRecord), err
}

func (t tagRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TagRecord, err error) {
	buf := make([]*model.TagRecord, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tagRecordDo) FindInBatches(result *[]*model.TagRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tagRecordDo) Attrs(attrs ...field.AssignExpr) ITagRecordDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tagRecordDo) Assign(attrs ...field.AssignExpr) ITagRecordDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tagRecordDo) Joins(fields ...field.RelationField) ITagRecordDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tagRecordDo) Preload(fields ...field.RelationField) ITagRecordDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tagRecordDo) FirstOrInit() (*model.TagRecord, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagRecord), nil
	}
}

func (t tagRecordDo) FirstOrCreate() (*model.TagRecord, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagRecord), nil
	}
}

func (t tagRecordDo) FindByPage(offset int, limit int) (result []*model.TagRecord, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tagRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tagRecordDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tagRecordDo) Delete(models ...*model.TagRecord) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tagRecordDo) withDO(do gen.Dao) *tagRecordDo {
	t.DO = *do.(*gen.DO)
	return t
}
