// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yeisme/pinax/internal/index/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newVaultFileRecord(db *gorm.DB, opts ...gen.DOOption) vaultFileRecord {
	_vaultFileRecord := vaultFileRecord{}

	_vaultFileRecord.vaultFileRecordDo.UseDB(db, opts...)
	_vaultFileRecord.vaultFileRecordDo.UseModel(&model.VaultFileRecord{})

	tableName := _vaultFileRecord.vaultFileRecordDo.TableName()
	_vaultFileRecord.ALL = field.NewAsterisk(tableName)
	_vaultFileRecord.Path = field.NewString(tableName, "path")
	_vaultFileRecord.Filename = field.NewString(tableName, "filename")
	_vaultFileRecord.Stem = field.NewString(tableName, "stem")
	_vaultFileRecord.Extension = field.NewString(tableName, "extension")
	_vaultFileRecord.MediaType = field.NewString(tableName, "media_type")
	_vaultFileRecord.Size = field.NewInt64(tableName, "size")
	_vaultFileRecord.ModifiedUnix = field.NewInt64(tableName, "modified_unix")
	_vaultFileRecord.ObjectKind = field.NewString(tableName, "object_kind")
	_vaultFileRecord.ManagedStatus = field.NewString(tableName, "managed_status")

	_vaultFileRecord.fillFieldMap()

	return _vaultFileRecord
}

type vaultFileRecord struct {
	vaultFileRecordDo

	ALL           field.Asterisk
	Path          field.String
	Filename      field.String
	Stem          field.String
	Extension     field.String
	MediaType     field.String
	Size          field.Int64
	ModifiedUnix  field.Int64
	ObjectKind    field.String
	ManagedStatus field.String

	fieldMap map[string]field.Expr
}

func (v vaultFileRecord) Table(newTableName string) *vaultFileRecord {
	v.vaultFileRecordDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v vaultFileRecord) As(alias string) *vaultFileRecord {
	v.vaultFileRecordDo.DO = *(v.vaultFileRecordDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *vaultFileRecord) updateTableName(table string) *vaultFileRecord {
	v.ALL = field.NewAsterisk(table)
	v.Path = field.NewString(table, "path")
	v.Filename = field.NewString(table, "filename")
	v.Stem = field.NewString(table, "stem")
	v.Extension = field.NewString(table, "extension")
	v.MediaType = field.NewString(table, "media_type")
	v.Size = field.NewInt64(table, "size")
	v.ModifiedUnix = field.NewInt64(table, "modified_unix")
	v.ObjectKind = field.NewString(table, "object_kind")
	v.ManagedStatus = field.NewString(table, "managed_status")

	v.fillFieldMap()

	return v
}

func (v *vaultFileRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *vaultFileRecord) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 9)
	v.fieldMap["path"] = v.Path
	v.fieldMap["filename"] = v.Filename
	v.fieldMap["stem"] = v.Stem
	v.fieldMap["extension"] = v.Extension
	v.fieldMap["media_type"] = v.MediaType
	v.fieldMap["size"] = v.Size
	v.fieldMap["modified_unix"] = v.ModifiedUnix
	v.fieldMap["object_kind"] = v.ObjectKind
	v.fieldMap["managed_status"] = v.ManagedStatus
}

func (v vaultFileRecord) clone(db *gorm.DB) vaultFileRecord {
	v.vaultFileRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v vaultFileRecord) replaceDB(db *gorm.DB) vaultFileRecord {
	v.vaultFileRecordDo.ReplaceDB(db)
	return v
}

type vaultFileRecordDo struct{ gen.DO }

type IVaultFileRecordDo interface {
	gen.SubQuery
	Debug() IVaultFileRecordDo
	WithContext(ctx context.Context) IVaultFileRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVaultFileRecordDo
	WriteDB() IVaultFileRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVaultFileRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVaultFileRecordDo
	Not(conds ...gen.Condition) IVaultFileRecordDo
	Or(conds ...gen.Condition) IVaultFileRecordDo
	Select(conds ...field.Expr) IVaultFileRecordDo
	Where(conds ...gen.Condition) IVaultFileRecordDo
	Order(conds ...field.Expr) IVaultFileRecordDo
	Distinct(cols ...field.Expr) IVaultFileRecordDo
	Omit(cols ...field.Expr) IVaultFileRecordDo
	Join(table schema.Tabler, on ...field.Expr) IVaultFileRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVaultFileRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVaultFileRecordDo
	Group(cols ...field.Expr) IVaultFileRecordDo
	Having(conds ...gen.Condition) IVaultFileRecordDo
	Limit(limit int) IVaultFileRecordDo
	Offset(offset int) IVaultFileRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVaultFileRecordDo
	Unscoped() IVaultFileRecordDo
	Create(values ...*model.VaultFileRecord) error
	CreateInBatches(values []*model.VaultFileRecord, batchSize int) error
	Save(values ...*model.VaultFileRecord) error
	First() (*model.VaultFileRecord, error)
	Take() (*model.VaultFileRecord, error)
	Last() (*model.VaultFileRecord, error)
	Find() ([]*model.VaultFileRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VaultFileRecord, err error)
	FindInBatches(result *[]*model.VaultFileRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.VaultFileRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVaultFileRecordDo
	Assign(attrs ...field.AssignExpr) IVaultFileRecordDo
	Joins(fields ...field.RelationField) IVaultFileRecordDo
	Preload(fields ...field.RelationField) IVaultFileRecordDo
	FirstOrInit() (*model.VaultFileRecord, error)
	FirstOrCreate() (*model.VaultFileRecord, error)
	FindByPage(offset int, limit int) (result []*model.VaultFileRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVaultFileRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v vaultFileRecordDo) Debug() IVaultFileRecordDo {
	return v.withDO(v.DO.Debug())
}

func (v vaultFileRecordDo) WithContext(ctx context.Context) IVaultFileRecordDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v vaultFileRecordDo) ReadDB() IVaultFileRecordDo {
	return v.Clauses(dbresolver.Read)
}

func (v vaultFileRecordDo) WriteDB() IVaultFileRecordDo {
	return v.Clauses(dbresolver.Write)
}

func (v vaultFileRecordDo) Session(config *gorm.Session) IVaultFileRecordDo {
	return v.withDO(v.DO.Session(config))
}

func (v vaultFileRecordDo) Clauses(conds ...clause.Expression) IVaultFileRecordDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v vaultFileRecordDo) Returning(value interface{}, columns ...string) IVaultFileRecordDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v vaultFileRecordDo) Not(conds ...gen.Condition) IVaultFileRecordDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v vaultFileRecordDo) Or(conds ...gen.Condition) IVaultFileRecordDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v vaultFileRecordDo) Select(conds ...field.Expr) IVaultFileRecordDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v vaultFileRecordDo) Where(conds ...gen.Condition) IVaultFileRecordDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v vaultFileRecordDo) Order(conds ...field.Expr) IVaultFileRecordDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v vaultFileRecordDo) Distinct(cols ...field.Expr) IVaultFileRecordDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v vaultFileRecordDo) Omit(cols ...field.Expr) IVaultFileRecordDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v vaultFileRecordDo) Join(table schema.Tabler, on ...field.Expr) IVaultFileRecordDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v vaultFileRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVaultFileRecordDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v vaultFileRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IVaultFileRecordDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v vaultFileRecordDo) Group(cols ...field.Expr) IVaultFileRecordDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v vaultFileRecordDo) Having(conds ...gen.Condition) IVaultFileRecordDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v vaultFileRecordDo) Limit(limit int) IVaultFileRecordDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v vaultFileRecordDo) Offset(offset int) IVaultFileRecordDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v vaultFileRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVaultFileRecordDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v vaultFileRecordDo) Unscoped() IVaultFileRecordDo {
	return v.withDO(v.DO.Unscoped())
}

func (v vaultFileRecordDo) Create(values ...*model.VaultFileRecord) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v vaultFileRecordDo) CreateInBatches(values []*model.VaultFileRecord, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v vaultFileRecordDo) Save(values ...*model.VaultFileRecord) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v vaultFileRecordDo) First() (*model.VaultFileRecord, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VaultFileRecord), nil
	}
}

func (v vaultFileRecordDo) Take() (*model.VaultFileRecord, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VaultFileRecord), nil
	}
}

func (v vaultFileRecordDo) Last() (*model.VaultFileRecord, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VaultFileRecord), nil
	}
}

func (v vaultFileRecordDo) Find() ([]*model.VaultFileRecord, error) {
	result, err := v.DO.Find()
	return result.([]*model.VaultFileRecord), err
}

func (v vaultFileRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VaultFileRecord, err error) {
	buf := make([]*model.VaultFileRecord, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v vaultFileRecordDo) FindInBatches(result *[]*model.VaultFileRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v vaultFileRecordDo) Attrs(attrs ...field.AssignExpr) IVaultFileRecordDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v vaultFileRecordDo) Assign(attrs ...field.AssignExpr) IVaultFileRecordDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v vaultFileRecordDo) Joins(fields ...field.RelationField) IVaultFileRecordDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v vaultFileRecordDo) Preload(fields ...field.RelationField) IVaultFileRecordDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v vaultFileRecordDo) FirstOrInit() (*model.VaultFileRecord, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VaultFileRecord), nil
	}
}

func (v vaultFileRecordDo) FirstOrCreate() (*model.VaultFileRecord, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VaultFileRecord), nil
	}
}

func (v vaultFileRecordDo) FindByPage(offset int, limit int) (result []*model.VaultFileRecord, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v vaultFileRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v vaultFileRecordDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v vaultFileRecordDo) Delete(models ...*model.VaultFileRecord) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *vaultFileRecordDo) withDO(do gen.Dao) *vaultFileRecordDo {
	v.DO = *do.(*gen.DO)
	return v
}
